### ISSUE TITLE
Add percentage options to InfiniteGrid

### ISSUE THREAD

**Issue by daybrush** [naver/egjs-infinitegrid#121]
## Description

add percentage options to InfiniteGrid

position ex) left, top
size ex) width, height

**Comment by quyctd** [comment]
Hello, may I ask is this feature is available?

**Comment by daybrush** [comment]
@quyctd 

Consider the next feature.

**Comment by daybrush** [comment]
@quyctd 

`@egjs/infinitegrid` 3.7.0 is released.

`percentage` option is added. use it.
