### ISSUE TITLE
Error when componentDidUnmount() is called

### ISSUE THREAD

**Issue by elitenoire** [naver/egjs-infinitegrid#138]
## Description

I'm navigating between routes in my react app. Basically, GridLayout has errors when unmounting

Error:
``` 
Uncaught TypeError: Cannot create property 'el' on string '1523626041325
 at GridLayout.componentWillUnmount (Layout.js:formatted:1)
```

**Comment by younkue** [comment]
```@egjs/react-layout``` 1.2.8 version has been deployed and its bugs fixed.
Please try it. Thank you.
