### ISSUE TITLE
Question: Why overlap in laying out card in grid?

### ISSUE THREAD

**Issue by elitenoire** [naver/egjs-infinitegrid#140]
## Description

In my gridlayout, the card component sometimes overlap when rendering, and if you resize the layout, sometimes it lays out correctly.
![gridlayout](https://user-images.githubusercontent.com/25673419/38774923-0743be8e-406b-11e8-821d-def3cfbc5679.png)
On resize:
![gridlayout-resize](https://user-images.githubusercontent.com/25673419/38774925-22fe8546-406b-11e8-9b87-79352902d44e.png)

This is the code for Grid Layout
```
<GridLayout
             tag="div"
             margin={16}
             align="center"
             isEqualSize={false}
                    >
                        {headlines.map((headline, index) => {
                        const { title, author, description, url, urlToImage, publishedAt, source} = headline
                        return (
                            <HeadlineCard
                                key={index + '-' + title}
                                title={title}
                                source={source.name}
                                author={author || source.name || 'Anonymous'}
                                url={url}
                                description={description}
                                urlImage={urlToImage}
                                date={publishedAt}
                            />
                        )
                        })}
                    </GridLayout>
```
The items it is rendering which is an array of HeadlineCard has some styles. The card has an image container which i gave a max width and also a height.

**Comment by younkue** [comment]
sorry, It's random-id bug.  ID is more unique with a combination of date and a larger random number.

```@egjs/react-layout``` 1.2.8 version has been deployed and its bugs fixed.
Please try it. Thank you.
