### ISSUE TITLE
Can't set  JustifiedLayout height in React.js

### ISSUE THREAD

**Issue by xVanTuring** [naver/egjs-infinitegrid#179]
## Description
I try to wrap the JustifiedLayout into a div, after set the width,height and overflow, when I scroll the div to the bottom,it doesn't load more image.

## Steps to check or reproduce

[Demo](https://codesandbox.io/s/vn367lxw60)

**Comment by xVanTuring** [comment]
Seems that it only need add className to the render func of the InfiniteGrid, and set the size in the .css file.

**Comment by younkue** [comment]
@xVanTuring 

oh. try this example.
```jsx
<JustifiedLayout
          threshold={250}
          onAppend={this.onAppend}
          margin={8}
          onLayoutComplete={this.onLayoutComplete}
          isOverflowScroll={true}
          style={{
                    height: 400,
                    width: 700,
        }}></JustifiedLayout>
```

**Comment by xVanTuring** [comment]
That works fine! Still have a problem, is there any way to re-layout manually, cos I want to resize item after loaded, then the layout become total mess, until next load.
