### ISSUE TITLE
Don't load after wrap layout into div

### ISSUE THREAD

**Issue by xVanTuring** [naver/egjs-infinitegrid#182]
## Description
I want to make the content in the center of its parent, so I wrap it into a div with margin '0 auto'. Like the #179 , after the initial load, when I scroll to the bottom, it doesn't load anymore.
If I use isOverflowScroll, the scroll bar will always be the right of the layout, which is not what I want.

## Steps to check or reproduce
[Demo](https://codesandbox.io/s/vn367lxw60)

**Comment by younkue** [comment]
We have no plans to support containers yet;;; :(

**Comment by xVanTuring** [comment]
How about adding Left-Right Padding to make the layout look more better.
