### ISSUE TITLE
Type declaration filename misspelling

### ISSUE THREAD

**Issue by todtod80** [naver/egjs-infinitegrid#204]
## Description
I found a type declaration filename misspelling.

https://github.com/naver/egjs-infinitegrid/blob/master/packages/react-infinitegrid/declaration/index.d.ts
```javascript
import FrameLayout from "./layouts/FrameLayout";
```

But `./layouts/FrmaeLayout.d.ts` exists.
- https://github.com/naver/egjs-infinitegrid/blob/master/packages/react-infinitegrid/declaration/layouts/FrmaeLayout.d.ts

## Steps to check or reproduce

1. Add module
```bash
npm install @egjs/react-infinitegrid
or
yarn add @egjs/react-infinitegrid
```

2. Use `import` syntax
```javascript
import { GridLayout } from '@egjs/react-infinitegrid'
```

**Comment by younkue** [comment]
```@egjs/react-infinitegrid``` 1.1.5 version has been deployed and its filename fixed.
