### ISSUE TITLE
Description for useRecycle

### ISSUE THREAD

**Issue by younkue** [naver/egjs-infinitegrid#205]
## Steps to check or reproduce

![userecycle](https://user-images.githubusercontent.com/3433062/43043912-44de40c0-8dd7-11e8-8969-e824fc88af49.gif)
![nouserecycle](https://user-images.githubusercontent.com/3433062/43043913-45050ef8-8dd7-11e8-8f6f-3ddbc5abe05c.gif)

---

![userecycle](https://user-images.githubusercontent.com/3433062/43628822-5b2def70-9736-11e8-88a4-ada172eceaae.gif)
![nouserecycle](https://user-images.githubusercontent.com/3433062/43628824-5b5795be-9736-11e8-8fe0-46387595dd7a.gif)

**Comment by jongmoon** [comment]
What is this issue? it can be closed?
