### ISSUE TITLE
React-InfiniteGrid, JustifiedLayout measure incorrect

### ISSUE THREAD

**Issue by xVanTuring** [naver/egjs-infinitegrid#210]
## Description
Try to add a little description below the image , but seems JustifiedLayout only use img's size.

## Steps to check or reproduce
[code sandbox example](https://codesandbox.io/s/r533romkpp)

**Comment by younkue** [comment]
JustifiedLayout use item's aspect ratio. this item's size depends on img's size.

like

https://www.google.co.kr/search?q=test&newwindow=1&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi0yPSY49zcAhXVdd4KHdvTCZgQ_AUICigB&biw=1673&bih=857

https://search.naver.com/search.naver?sm=tab_hty.top&where=image&query=test&oquery=d&tqi=T2qbkspySEZssveFQsdssssstxZ-014323
