### ISSUE TITLE
How to avoid waiting for all images to fully load before appending to GridLayout?

### ISSUE THREAD

**Issue by leobudima** [naver/egjs-infinitegrid#211]
## Description
Hi - first of all, thanks so much for these amazing components, I found them after a lot of searching and they are exactly what I needed, so huge thanks for your effort and sharing this!

I'm using the GridLayout for a gallery of images, and, using `onAppend`, I'm calling my server to get me a list of next 15 images to load (urls etc). The problem I have is that the GridLayout gets updated only when all 15 images have completely finished loading, which takes a bit and causes a lot of UI delay... 

Is it possible somehow to add images one by one as they load, or add the IMG elements to the list no matter the status of image loading?

Here's my code:

```
async getFeedPublic(payload = {}, state) {

	let url = ENV.API + URL.feedPublic + '?limit=' + state.limit + '&skip=' + state.skip;

	const response = await fetch(url);
	const data = await response.json();

	const uiItems = data.map((item, index) => {
                 // PhotoFeedItem contains an IMG tag that loads the image
		return <PhotoFeedItem key={state.skip + index} groupKey={payload.groupKey} photo={item} />;
	});
	// practically sets props.items in FeedList
	this.updateUIItems(uiItems);
}

const onAppend = async (e, props) => {
	const groupKey = parseFloat(e.groupKey || 0) + 1;
	props.getFeedPublic({ groupKey: groupKey });
};

const FeedList = (props) => {
	return (
		<div className="feed-container">
			<GridLayout
				className="feed"
				id="feed-container"
				margin={15}
				threshold={500}
				align="center"
				useFit={false}
				onAppend={(e) => {
					onAppend(e, props);
				}}
			>
				{props.items}
			</GridLayout>
		</div>
	);
};
```

Thanks a lot for any help!

**Comment by younkue** [comment]
InfiniteGrid supports image-loading by adding the data-width and data-height attributes to img tag.

**Comment by leobudima** [comment]
Hi @younkue - thanks a lot for your response - that's great; when trying before, I added those attributes to the div that wraps the img and it didn't work, so I didn't realize that was the intended effect. Works great when added to the img tag itself. Thanks again!
