### ISSUE TITLE
If you scroll back to top after resizing items do not line up with header

### ISSUE THREAD

**Issue by baxtr** [naver/egjs-infinitegrid#213]
## Description

I've noticed if you scroll down the grid layout page and then resize the window the items will not align with the top of your page header if you scroll back to the top. If you resize the window again then will realign with the header. This can be easily reproduced in the grid layout demo.

https://naver.github.io/egjs-infinitegrid/assets/html/grid.html

**Comment by younkue** [comment]
@baxtr 

Thank you. I'll fix it as soon as possible.

**Comment by baxtr** [comment]
Thanks, can this fix also be updated for react-infinitegrid?

**Comment by younkue** [comment]
@baxtr 

I only modified the demo.

Do you see https://codesandbox.io/s/52n7437k8n?

react-infinitegrid's demo use [isConstantSize](https://naver.github.io/egjs-infinitegrid/#isconstantsize-defaultfalse)

It works fine without modification.

**Comment by baxtr** [comment]
Oh ok, that worked. Thanks again.
