### ISSUE TITLE
bug: TypeError: Right-hand side of 'instanceof' is not an object when use jQuery.noConfilct(true)

### ISSUE THREAD

**Issue by belozer** [naver/egjs-infinitegrid#223]
## Description
TypeError: Right-hand side of 'instanceof' is not an object when use jQuery.noConfilct(true)

## Steps to check or reproduce
1. add jquery and run `window.jQuery.noConfilct(true)`
2. Set container 

```js
const ig = new InfiniteGrid(myHTMLElementContainer);
ig.setLayout(InfiniteGrid.GridLayout, { align : 'justify' });
ig.layout();
```
Problem in this string https://github.com/naver/egjs-infinitegrid/blob/534cf113593e033be1f4565706ade6c842cdb186/src/utils.js#L59

**Comment by belozer** [comment]
Maybe better use `typeof`?
` } else if (typeof window.jQuery !== 'undefined' && param instanceof window.jQuery) ||`

**Comment by jongmoon** [comment]
@belozer Thank you for reporting. 👍

**Comment by younkue** [comment]
@belozer 

Thank you for reporting. It has been fixed. ```@egjs/infinitegrid``` 3.4.4 version has been deployed
