### ISSUE TITLE
Angular Support Please!

### ISSUE THREAD

**Issue by NiNJAD3vel0per** [naver/egjs-infinitegrid#266]
This is a Great project. I really want to utilize this grid library in my project. 
But I am an **Angular**(+7) developer.
 I've researched source codes because it was written in **Typescript**.
I created a wrapper project called ng-eginfinitegrid and imported the source files in my src folder to utilize it. Of course, I also added egjs-component as well. 
I could use the main classes(InfiniteGrid/GridLayout) successfully with no error. But, the layout rendering is very unstable and even doesn't show up anything properly. I inspected Dom rendered part through the chrome dev tools. It looked no problem but I don't know why. Maybe I need study Angular rendering system more but it should have worked it. !

I almost gave up to make a wrapper for this myself; I've spent too much time for this. The core part of egjs is out of my hand because I need to understand the whole source code how to work inside. It looks very complicated for me in terms of Dom Rendering. 
Could you make a basic wrapper for Angular please?

This is my naive code to show you how I connected the egjs classes. 

```
export class GridComponent implements OnInit {
	@ViewChild('mygrid') _myGrid: ElementRef;
	@ViewChild('mytempl') _mytemp: ElementRef;
	@ViewChild('mainarea') _mainarea: ElementRef;

...............

                 let mytemp: HTMLElement = this._mytemp.nativeElement as HTMLElement;
		console.log('_mytemp.elementRef: ', mytemp);

		let mytemp_array2: HTMLElement[] = [];
		//let mytemp_array: HTMLElement[] = [ mytemp, mytemp, mytemp, mytemp ];
		//let ig = new InfiniteGrid(document.getElementById('gridapp'));
		let ig = new InfiniteGrid(document.getElementById('gridapp'));
		let num = 21;
		let layout = new GridLayout({
			margin: 30,
			align: 'center'
		});

		ig.setLayout(layout, { itemSize: 200 });


    let  test : NgElement = mytemp as NgElement;

    let template = '<div class="item"><div class="thumbnail"><img src="assets/mypic3.jpg"></div><div class="info"></div></div>';

		ig.on({
			append: function(e) {

				for (var i = 0; i < num; ++i) {
					mytemp_array2.push(mytemp);
				}
			//	console.log(mytemp_array2);
                               ig.append(mytemp_array2, e.groupKey + 1);
                                //ig.updateItems();
			},
			layoutComplete: function(e) {
				e.target.forEach(function(item) {
					if (!item.el) {
						return;
					}
					// add animation
					//item.el.setAttribute('class', 'item animate');
				});
				if (!e.isAppend && e.fromCache && e.target[0].groupKey === 0) {
					ig.layout(true);
				}
			}
    });

		for (var i = 0; i < num; ++i) {
			mytemp_array2.push(mytemp);
		}
		// console.log('mytemp: ', mytemp);
		// console.log(mytemp_array2);
    ig.append(mytemp_array2, 0);
```

**template.html**

```
<div class="search">
  <div class="header">
    <div class="header-container">
    </div>
  </div>
  <div #mainarea id="gridapp" class="container">
    <div class="contents">

    </div>

  </div>
</div>
<!--
<div #mytempl id="mypics1">
        <img  id="mypics2" src="https://www.google.com/logos/doodles/2019/martin-luther-king-jr-day-2019-5671880349450240-s.png" width="350" height="350px">
  </div> -->
  <div #mytempl id="mypics1">
      <img  id="mypics2" src="assets/mypic2.jpg" width="350" height="350px">
</div>
```

**Comment by NiNJAD3vel0per** [comment]
How is it going ?

**Comment by daybrush** [comment]
@NiNJAD3vel0per 
I'm sorry to have kept you waiting.
There is a lot of work to be done on other components at the schedule is very much behind.
Work on InfiniteGrid's side is likely to begin in the third or fourth week of May.

**Comment by daybrush** [comment]
@NiNJAD3vel0per 
The schedule is much late. It will be deployed this week.

PR and beta are in progress.

```
npm i @egjs/ngx-infinitegrid
```

https://github.com/daybrush/egjs-infinitegrid/tree/ngx-infinitegrid3%23266/packages/ngx-infinitegrid

The following example is provided.
* [GridLayout Demo](https://codesandbox.io/s/ngx-infinitegrid-demo-gridlayout-vu7pp)
* [GridLayout with Parallax Demo](https://codesandbox.io/s/ngx-infinitegrid-parallax-demo-gridlayout-cvxg5)
* [JustifiedLayout Demo](https://codesandbox.io/s/ngx-infinitegrid-demo-justifiedlayout-ypvf7)
* [Youtube Demo](https://codesandbox.io/s/ngx-infinitegrid-youtube-demo-m1npy)

**Comment by daybrush** [comment]
@NiNJAD3vel0per 

`@egjs/ngx-infinitegrid` 3.0.0 is released. Thank you.
