### ISSUE TITLE
Safari IOS blur() causes grid to disappear

### ISSUE THREAD

**Issue by baxtr** [naver/egjs-infinitegrid#274]
## Description

I've noticed this bug only on IOS devices with safari. I'm using document.activeElement.blur() to close the soft keyboard after a search submit. If this fires before the render it causes the infinitegrid to display no data and my contents to disappear. However, this only happens if you submit a search after scrolling to page two which uses onAppend to add more data. My workaround was to use in blur() only in onLayoutComplete. Any ideas why this is happening.

**Comment by younkue** [comment]
@baxtr

Thank you for registering your inquiry.

But I don't know what you wrote, so do you have any photo or test address?
