### ISSUE TITLE
Not apply minSize and maxSize opptions.(minSize와 maxSize옵션이 적용이 안 됩니다.)

### ISSUE THREAD

**Issue by cizz3007** [naver/egjs-infinitegrid#292]
## Description
React환경입니다.
다른 부분은 적용의 이상이 없습니다. 하지만 minSize와 maxSize 옵션이 적용이 안 되는 것 같습니다. 
아니면 제가 잘 못 사용하는 걸까요 ? 
한 행에 이미지가 최대 column 미만으로 들어가 있을 경우 각각의 이미지 객체가 화면을 양분하여 꽉찹니다. (마진 값을 포함해서 서로 화면을 이등분합니다.). 의도한 대로 겠지만 그렇게 되며 이미지가 너무 커지게 되어 이미지의 최대 크기에 제한을 주고 싶어 max-size 옵션을 줘도 먹히지 않는 것 같습니다. css로 max-width를 준다한 들 다음 이미지가 한 행을 잡아먹고 간격이 어긋납니다.
masonry에서  naver egjs로 마이그레이션 최종 단계인데 이 부분만 문제를 일으켜서 답을 찾고자 합니다.

## Steps to check or reproduce
`    <JustifiedLayout
                                tag={'ul'}
                                margin={10}
                                align={'left'}
                                column={viewCount}
                                useFit={false}
                                minSize={120}
                                maxSize={240}
                                useRecycle={false}
                                transitionDuration={0.2}
                                isConstantSize={true}
                                onChange={this.onChange}
                                onAppend={this.onAppend}
                                onLayoutComplete={this.onLayoutComplete}>
                                {
                                    list
                                }
                            </JustifiedLayout>`

**Comment by daybrush** [comment]
안녕하세요

**Comment by cizz3007** [comment]
안녕하세요삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------발신: "Daybrush (Younkue Choi)" <notifications@github.com> 날짜: 19/9/6  오후 8:00  (GMT+09:00) 받은 사람: naver/egjs-infinitegrid <egjs-infinitegrid@noreply.github.com> 참조: cizz3007 <cizz3007@gmail.com>, Author <author@noreply.github.com> 제목: Re: [naver/egjs-infinitegrid] minSize와 maxSize옵션이 적용이 안 됩니다. (#292) 안녕하세요



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/naver/egjs-infinitegrid/issues/292?email_source=notifications\u0026email_token=AHZNIXVVXT5QGUDCZTJSSBTQIIZ57A5CNFSM4IUHPO6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6CQGOY#issuecomment-528810811",

"url": "https://github.com/naver/egjs-infinitegrid/issues/292?email_source=notifications\u0026email_token=AHZNIXVVXT5QGUDCZTJSSBTQIIZ57A5CNFSM4IUHPO6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6CQGOY#issuecomment-528810811",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by daybrush** [comment]
@cizz3007 

안녕하세요.
minSize와 maxSize가 제대로 적용하지 않는 경우가 있습니다.
한 행에 최소, 최대개수를 정할 수 있는 column 옵션이 있습니다.
column 옵션의 기본값이 [1,8]이기 때문에 이미지들을 한 행에 최대 8개까지 넣을 수 있습니다.

그렇기 때문에 최소 1개, 최대 8개를 넣어야 되고 비율을 유지한 채로 minSize 가 120 maxSize 240 사이를 유지해야 하는데 정상적으로 보이지 않다는 것은 해를 찾지 못해 불가능하다는 것을 나타내면서 근사값으로 보여주는 것 같습니다.

정상적으로 나타내기 위해서는 column의 최대 개수를 늘리는 것을 추천드립니다.
