### ISSUE TITLE
npm으로 설치시 getComputedStyle 에러가 나타납니다.

### ISSUE THREAD

**Issue by finn000** [naver/egjs-infinitegrid#302]
` $ npm install @egjs/infinitegrid` 설치

```
import InfiniteGrid, { GridLayout, JustifiedLayout } from "@egjs/infinitegrid";

var ig = new InfiniteGrid("#grid", {
    horizontal: false,
});

ig.setLayout(GridLayout, {
    itemSize: 200,
});
```

설치 가이드대로 진행했으나

![error](https://user-images.githubusercontent.com/50653943/68840611-6aba1680-0706-11ea-81d2-7f83d2c11b08.png)
위와 같은 에러 발생합니다.

**Comment by daybrush** [comment]
@finn000 

안녕하세요.

아마도 grid라는 아이디를 가진 엘리먼트가 없거나 로드 전에 InfiniteGrid 인스턴스를 생성하시는 것 같습니다.
다시 확인해보실 수 있나요?


---
Hi ~

Maybe there is no element with `grid` id and you create an InfiniteGrid instance before it is loaded.
Can you check again?
