### ISSUE TITLE
InfiniteGrid with perfect scrollbar

### ISSUE THREAD

**Issue by dustin-shelton** [naver/egjs-infinitegrid#306]
## Description

How can I integrate InfiniteGrid with perfect scrollbar, as perfect scrollbar add overflow: hidden,

append method is not getting called.

**Comment by daybrush** [comment]
@dustin-shelton 

It is recommended that you use `isOverflowScroll: true` option.

**Comment by dustin-shelton** [comment]
Please find the code pan for Infinite grid with perfect scroll bar.

 perfect scroll bar scroller does not appear as it.

https://codepen.io/dshelton/pen/dyPzVNr?&editable=true

[perfect-scrollbar](https://github.com/mdbootstrap/perfect-scrollbar)

**Comment by daybrush** [comment]
@dustin-shelton 

Would you like to move your code last?

```js
ig.append(getItems(num * 2), 0);

const ps = new PerfectScrollbar('.parent',{
 
});
```

**Comment by dustin-shelton** [comment]
@daybrush Thanks it is working now.
