### ISSUE TITLE
Image overlap, Wait for all image to load

### ISSUE THREAD

**Issue by dustin-shelton** [naver/egjs-infinitegrid#307]
Sometimes if the image is taking time to load on browser, the Images are overlapping.
Is there any way to avoid situation?

**Comment by xVanTuring** [comment]
You can try adding `data-height` and `data-width` to your img element. https://github.com/naver/egjs-infinitegrid/issues/211#issuecomment-412507322

**Comment by vijay-ftxinfotech** [comment]
How to show placeholder image until image loads.

**Comment by vijay-ftxinfotech** [comment]
By adding data-height and data-width, Dom Recycle is not working.

**Comment by daybrush** [comment]
@vijay-ftxinfotech 

Probably because of this issue.

https://github.com/naver/egjs-infinitegrid/pull/319

I will let you know again if I solve it.

**Comment by daybrush** [comment]
@vijay-ftxinfotech 

Updated to new version.

Try again

**Comment by JoaquinMayer** [comment]
I still have overlaping problem if it's not an image tag.

How can I solve it?

**Comment by daybrush** [comment]
@JoaquinMayer 

Is there any demo address I can test?

**Comment by JoaquinMayer** [comment]
> @JoaquinMayer
> 
> Is there any demo address I can test?

Yes, here you can check it. [Example](https://codesandbox.io/s/dazzling-allen-mi331)

If you remove the anchor tag, you can see it great!

**Comment by daybrush** [comment]
@JoaquinMayer 

Check image css
```css
div img {
  width: 100%;
  height: auto;
}
```

**Comment by diegonyc** [comment]
Hi, I put the `data-width,data-height,width,height` attributes and still waits for all the images to load.  In my case, I am using the `4.7.1` version and the `MasonryInfiniteGrid` from `@egjs/svelte-infinitegrid`.

Can you help me?

I like that the images start downloading at the same time. But, sometimes one out of five images takes 10 times longer in my case. It is bad for user experience to have to wait for that one while the other four are already loaded.
