### ISSUE TITLE
 Cannot read property 'check' of undefined | where is ImageLoaded from "@egjs/infinitegrid"?

### ISSUE THREAD

**Issue by Anenth** [naver/egjs-infinitegrid#322]
## Description

I am trying out with `@egjs/react-layout` and I am getting ` Cannot read property 'check' of undefined` error from the https://github.com/naver/egjs-infinitegrid/blob/master/packages/react-layout/src/Layout.js#L224

When I looked at the code I couldn't find any `ImageLoaded` in "@egjs/infinitegrid";

how to fix this?

**Comment by daybrush** [comment]
@Anenth 

`@egjs/react-layout` 1.4.1 is released. thank you.
