### ISSUE TITLE
Cannot read property 'tagName' of undefined

### ISSUE THREAD

**Issue by GitHubish** [naver/egjs-infinitegrid#324]
I have the error "Cannot read property 'tagName' of undefined" which appears systematically on Angular. The grid is displayed if I don't set the isOverflowScroll option to true even if the error occurs several times. But if I set it to true the grid is not displayed at all. Cannot find the cause of the problem.

```
ERROR TypeError: Cannot read property 'tagName' of undefined
    at lazyloaded.esm.js:221
    at Array.forEach (<anonymous>)
    at check (lazyloaded.esm.js:220)
    at RenderManager.__proto.render (infinitegrid.esm.js:1656)
    at next (infinitegrid.esm.js:3447)
    at NgxGridLayoutComponent.next [as nextFunction] (infinitegrid.esm.js:3511)
    at NgxGridLayoutComponent.ngAfterViewChecked (egjs-ngx-infinitegrid.js:155)
    at callProviderLifecycles (core.js:32331)
    at callElementProvidersLifecycles (core.js:32293)
    at callLifecycleHooksChildrenFirst (core.js:32275)

```

**Comment by daybrush** [comment]
@GitHubish 

Thanks for the bug report. Can you tell me the version of ngx-infinitegrid that I used to test?

**Comment by GitHubish** [comment]
Hello I use the latest version to know: "@egjs/ngx-infinitegrid": "^3.0.3"

My html code is this one:

```
<div class="gridlayout" NgxGridLayout [options]="options" [layoutOptions]="layoutOptions" [items]="items"
  [trackBy]="trackBy" [groupBy]="groupBy" (append)="onAppend($event)" #ig>
  <my-card class="card-item" [content]="item.data" *ngFor="let item of ig.visibleItems;trackBy: trackBy;">
  </my-card>
</div>
```

And my setup: 

```
  options = {
    isOverflowScroll: true,
    useFit: true,
    useRecycle: true,
    horizontal: false
  };
  layoutOptions = {
    margin: 10,
    align: "start"
  };
```

Thanks

**Comment by daybrush** [comment]
@GitHubish 

My guess is that the item's key is a duplicate.

Check the trackBy function.

**Comment by GitHubish** [comment]
Apparently no, if I understood your hypothesis correctly. Here is what is logged in the console when the onAppend function is executed for the first time. 

```
0: {groupKey: 1, key: 0, num: 0, data: {…}}
1: {groupKey: 1, key: 1, num: 1, data: {…}}
2: {groupKey: 1, key: 2, num: 2, data: {…}}
3: {groupKey: 1, key: 3, num: 3, data: {…}}
4: {groupKey: 1, key: 4, num: 4, data: {…}}
5: {groupKey: 1, key: 5, num: 5, data: {…}}
6: {groupKey: 1, key: 6, num: 6, data: {…}}
7: {groupKey: 1, key: 7, num: 7, data: {…}}
8: {groupKey: 1, key: 8, num: 8, data: {…}}
9: {groupKey: 1, key: 9, num: 9, data: {…}}
10: {groupKey: 1, key: 10, num: 10, data: {…}}
11: {groupKey: 1, key: 11, num: 11, data: {…}}
12: {groupKey: 1, key: 12, num: 12, data: {…}}
13: {groupKey: 1, key: 13, num: 13, data: {…}}
14: {groupKey: 1, key: 14, num: 14, data: {…}}
15: {groupKey: 1, key: 15, num: 15, data: {…}}
16: {groupKey: 1, key: 16, num: 16, data: {…}}
17: {groupKey: 1, key: 17, num: 17, data: {…}}
18: {groupKey: 1, key: 18, num: 18, data: {…}}
19: {groupKey: 1, key: 19, num: 19, data: {…}}
20: {groupKey: 1, key: 20, num: 20, data: {…}}

core.js:5873 ERROR TypeError: Cannot read property 'tagName' of undefined
    at lazyloaded.esm.js:221
    at Array.forEach (<anonymous>)
    at check (lazyloaded.esm.js:220)
    at RenderManager.__proto.render (infinitegrid.esm.js:1656)
    at next (infinitegrid.esm.js:3447)
    at NgxGridLayoutComponent.next [as nextFunction] (infinitegrid.esm.js:3511)
    at NgxGridLayoutComponent.ngAfterViewChecked (egjs-ngx-infinitegrid.js:506)
    at callHook (core.js:3941)
    at callHooks (core.js:3901)
    at executeCheckHooks (core.js:3823)
```

**Comment by daybrush** [comment]
@GitHubish 

Can you show me the trackBy function?

**Comment by GitHubish** [comment]
@daybrush These are my two functions. Thanks  

```
groupBy(index: number, item: any) {
  return item.groupKey;
}

trackBy(index: number, item: any) {
  return item.key;
}
```

**Comment by daybrush** [comment]
@GitHubish 

Do you compare with this? I've implemented similar but it's not reproducible.

https://codesandbox.io/s/ngx-infinitegrid-demo-gridlayout-7diu5

**Comment by GitHubish** [comment]
Yes, that's right. I will try to create from your Stackblitz an example similar to my app to try to find out what generates the problem. Instead of images, for my part it's a card component that may or may not have an image.

Thanks

**Comment by GitHubish** [comment]
Here is an example of where the problem occurs. This is basically the code I have in my prototype 

https://codesandbox.io/s/ngx-infinitegrid-demo-gridlayout-4fnzp

**Comment by daybrush** [comment]
@GitHubish 

Thanks to your demo. I found the reason I will fix and release soon.

Thank you :)

**Comment by GitHubish** [comment]
Great, thanks!
I'm looking forward to the patch to move forward with my integration.

**Comment by daybrush** [comment]
@GitHubish 

`@egjs/ngx-infinitegrid` 3.0.4 is released. Check it again. Thank you :)

**Comment by GitHubish** [comment]
Great @daybrush! Good job, guys. There's no more mistakes with this example.

I managed to reproduce the error in one case, in a previous test, I have a filtering of the list and so I refresh the list. So I used the method : 

`this.ig.updateItems();`

And just when I call this method it reproduces the same error. However this call is not necessary in my case. Maybe you'd like to see if there is also a fix to be made when calling this method or maybe it's me who shouldn't call it at this time.

Thank you for the reactivity!

**Comment by daybrush** [comment]
@GitHubish 

Perhaps that depends on when you call that method.

Can you show me how to reproduce when it is called in the demo?

**Comment by Zokor** [comment]
The same happens to me. 

But i added an ngIf before. in hope for the library to process something.

If i remove it it doesn't throw an error, but it doesn't show anything.

**Comment by daybrush** [comment]
@Zokor 

Is the target added with ngif an infinitegrid? Or is it an item?

**Comment by msqaddura** [comment]
you should use `itemKey ` instead of `key`
`0: {groupKey: 1, key: 0, num: 0, data: {…}}`

becomees
`0: {groupKey: 1, key: 0, itemKey:0, num: 0, data: {…}}`

**Comment by msqaddura** [comment]
Just to add my bits here, this issue is related to `isOverflowScroll:true` if otherwise it is put to false then everything is good.

**Comment by daybrush** [comment]
@msqaddura @GitHubish @Zokor 

ngx-infinitegrid has been updated. I'm not sure if your phenomenon has been resolved, but try updating it.
