### ISSUE TITLE
useRecycle not working

### ISSUE THREAD

**Issue by DimaHalimanov** [naver/egjs-infinitegrid#325]
## Description
Hello everyone. I am using react-infinitygrid and noticed that the useRecycle option is not working.

## Steps to check or reproduce
Link to codeSandBox: [https://codesandbox.io/s/030opyqkvw](https://codesandbox.io/s/030opyqkvw)

**Comment by daybrush** [comment]
@DimaHalimanov 

Hi I tried useRecycle to false and it seems to be working properly.

```jsx
<GridLayout
        options={{
          isConstantSize: true,
          transitionDuration: 0.2,
          useRecycle: false,
        }}
        layoutOptions={{
          margin: 10,
          align: "center"
        }}
        onAppend={this.onAppend}
        onLayoutComplete={this.onLayoutComplete}
      >
        {this.state.list}
      </GridLayout>
```

**Comment by DimaHalimanov** [comment]
Can you show the demo on codesandbox?

**Comment by DimaHalimanov** [comment]
I tried useRecycle to false and it's working properly. But when I tried useRecycle to true then it's not working properly.

**Comment by daybrush** [comment]
@DimaHalimanov 

Oh sorry. I was mistaken. useRecycle defaults to true and the demo's groupKey setting is wrong. Check out the demo again and it should work.
