### ISSUE TITLE
Position not ok when one column on vue-infinitegrid

### ISSUE THREAD

**Issue by saerose** [naver/egjs-infinitegrid#328]
## Description
When I add items to my array when I have one column (mobile) the items are added to it but I cannot see them unless I resize the screen, I inspected the code with dev tools and the position of the elements is not correct:
`style="position: absolute; left: -100000px; top: -100000px;"`

It changes to the correct one after I resize the screen but it should appear correct when I load the new elements. This behaviour does not happen when I have two or more columns on my grid.

Any ideas on why this is happening?

**Comment by daybrush** [comment]
@saerose 

Is there any demo I can test?

**Comment by akshaybosamiya** [comment]
I'm having the similar issue while using react version(react-infinitegrid) of lib. Please guide me if any one know to fix it.

![Screenshot from 2020-07-16 21-39-06](https://user-images.githubusercontent.com/11747938/87695402-15f70000-c7ad-11ea-8234-00bcb0ad9231.png)

**Comment by daybrush** [comment]
@akshaybosamiya 

Could you show me how to use InfiniteGrid JSX?

**Comment by akshaybosamiya** [comment]
> @akshaybosamiya
> 
> Could you show me how to use InfiniteGrid JSX?

Below is the my component code.

```jsx

import React, { Component } from "react";
import PropTypes from "prop-types";
import { connect } from "react-redux";
import { GridLayout } from "@egjs/react-infinitegrid";
import { ShowCenterSpinner } from "./statelessView";

class InfiniteGalleryGridLayout extends Component {
  constructor(props) {
    super(props);
    this.groupKey = 0;
    this.gridRef = React.createRef();
  }

  render() {
    const { childElements, hasMore, className } = this.props;

    return (
      <div className={`grid-gallary ${className}`}>
        <GridLayout
          ref={(node) => (this.gridRef = node)}
          className="gridlayout gridlayout-container"
          groupBy={(item) => item.props["data-groupkey"]}
          loading={
            <div className="loading">
              <ShowCenterSpinner loaded={!hasMore} />
            </div>
          }
          options={{
            isOverflowScroll: true,
            useFit: true,
            useRecycle: false,
            horizontal: false,
            // isConstantSize: false,
            threshold: 500,
            // isEqualSize: false,
          }}
          layoutOptions={{
            margin: 15,
            align: "center",
          }}
          onLayoutComplete={(e) => {
            // console.debug("onLayoutComplete: ", e);
            return !e.isLayout && e.endLoading();
          }}
          onAppend={(e) => {
            // console.debug("onAppend: ", e);
            if (!hasMore) {
              e.stop();
              return;
            }
            if (e.currentTarget.isProcessing() || e.currentTarget.isLoading()) {
              return;
            }
            this.groupKey =
              (typeof e.groupKey === "undefined" ? 0 : +e.groupKey || 0) + 1;
            e.startLoading();
            setTimeout(() => {
              this.loadNextPage(this.groupKey);
            }, 1000);
          }}
        >
          {childElements}
        </GridLayout>
      </div>
    );
  }

  componentWillUnmount() {}

  componentDidMount() {
  }

  loadNextPage = (groupKey) => {
    // Execute call from Parent components
    this.props.loadPage(groupKey);
  };
}

GalleryGridLayout.propTypes = {};
GalleryGridLayout.defaultProps = {
  className: "",
};

const mapStateToProps = (state) => ({});

const mapDispatchToProps = (dispatch) => ({});

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(InfiniteGalleryGridLayout);

```

**Comment by daybrush** [comment]
@akshaybosamiya 

In my opinion, the key of group 1 and group 2 of childElements is duplicated.

**Comment by akshaybosamiya** [comment]
> @akshaybosamiya
> 
> In my opinion, the key of group 1 and group 2 of childElements is duplicated.

Ok Thanks, I've checked it out just. But, its having unique key and group key.

![Screenshot from 2020-07-17 19-02-49](https://user-images.githubusercontent.com/11747938/87791711-5bc0d080-c860-11ea-9d35-fdfe58a0ebf5.png)

**Comment by akshaybosamiya** [comment]
@daybrush ,

Upto 2 page load, it works properly. But when I try to load/scroll up 3rd time, it messed the position of the second loaded group.

Video link: https://drive.google.com/file/d/1F2A16hpMlCIa7c9DJwjznI1fEOzm2_AQ/view?usp=sharing

**Comment by daybrush** [comment]
@akshaybosamiya 

Does the key change each time it is rendered? Does the key change each time it is rendered?

**Comment by akshaybosamiya** [comment]
> @akshaybosamiya
> 
> Does the key change each time it is rendered? Does the key change each time it is rendered?

Hi @daybrush,

I've just checked it out. It remains the same for each renders for the same item/image.

**Comment by daybrush** [comment]
@akshaybosamiya 

I made an example. Have you ever tried to copy and paste your code as much as possible. Is there a difference?
https://codesandbox.io/s/confident-jackson-rz7lo?file=/src/App.js:321-331

**Comment by akshaybosamiya** [comment]
> @akshaybosamiya
> 
> I made an example. Have you ever tried to copy and paste your code as much as possible. Is there a difference?
> https://codesandbox.io/s/confident-jackson-rz7lo?file=/src/App.js:321-331

Only difference is that I'm passing childelements from the parent component. In your code, childelements are getting generated in the same component.

**Comment by daybrush** [comment]
@akshaybosamiya 

Can I know the jsx of childElements?

**Comment by akshaybosamiya** [comment]
@daybrush,

Yes, sure.

```jsx
        <div
          key={`${image.id}_${Date.now()}`}
          className="item"
          data-groupkey={image.groupKey}
        >
          <ImageItem
            key={`${image.id}_${Date.now()}`}
            url={image.urls.thumb}
            alt={image.alt_description}
            width={image.width}
            height={image.height}
          />
        </div>
```

I'll try to share the codesandbox link with you today or may be tomorrow.

**Comment by daybrush** [comment]
@akshaybosamiya 

key={`${image.id}_${Date.now()}`}
is't it true that the key doesn't change when rendering?

![](https://user-images.githubusercontent.com/11747938/87791711-5bc0d080-c860-11ea-9d35-fdfe58a0ebf5.png)

It seems that the key changes every time it is rendered.


Aren't you writing this way in the parent component?
```js
const childElements = images.map(image => ....)
```

**Comment by akshaybosamiya** [comment]
@daybrush, 

Oh! My bad. Yeah, Key will differ on render. I understood group key. 

Thanks a lot for the torubleshooting.
