### ISSUE TITLE
Loading slot on vue-infinitegrid

### ISSUE THREAD

**Issue by saerose** [naver/egjs-infinitegrid#329]
## Description
I get the `TypeError: Cannot read property 'tagName' of undefined` when adding the loading slot.

**Comment by saerose** [comment]
Hi?

**Comment by WoodNeck** [comment]
Hello, @saerose.
Can you check whether your items include duplicated items? As that can cause the same error.
See #305 :)

**Comment by saerose** [comment]
I copy-pasted the example provided on the read me, I get the same error. :(

**Comment by daybrush** [comment]
@saerose 

Can you show me how you wrote the vue-infinitegrid?
