### ISSUE TITLE
What is the best way that process data through ajax?

### ISSUE THREAD

**Issue by cizz3007** [naver/egjs-infinitegrid#332]
```javascript
 onAppend = (e) => {
    if (this.ig && this.ig.isProcessing()) {
      return
    }
    e.startLoading()

    console.log('# append')

    const groupKey = parseFloat(e.groupKey || 0) + 1

    const index = this.state.index

    const payload = {
      regionid: 3124,
      index: index,
      groupKey: groupKey
    }
  //리덕스-사가 디스패치
    this.fetchData(payload)
    e.endLoading()

  }
```
바닥에 닿을 때 마다 새로운 데이터 배열을 가져오는 비동기 통신을 요청하고자 하는데
현재 이렇게 하려고 하는데 영 아닌 거 같고, 난해합니다.
어떤 방법으로 해야 될지 약간 막막해서 물어봅니다.

**Comment by daybrush** [comment]
@cizz3007 
안녕하세요. `startLoading()`과 `endLoading()` 은 비동기 통신이 되는 동안 추가적인 onAppend를 막기 위해 사용합니다.
endLoading을 제외한 나머지는 문제가 없을 것 같습니다.

그래서 fetchData가 끝난 후거나 onLayoutComplete에 호출하시면 될 것 같습니다.

```js
onLayoutComplete = e => {
    !e.isLayout && e.endLoading();
}
```

---
Hi. `startLoading ()` and `endLoading ()` are used to prevent additional onAppend during loading asynchronous data.

There seems to be no problem with the rest except endLoading.

So, after fetchData is over, you can call onLayoutComplete.


```js
onLayoutComplete = e => {
    !e.isLayout && e.endLoading();
}
```
