### ISSUE TITLE
@egjs/ngx-infinitegrid moveTo MIRRORS the order upwards

### ISSUE THREAD

**Issue by msqaddura** [naver/egjs-infinitegrid#337]
## Description
So when you use `moveTo(item)` everything above that item will be added in mirrored order.

## Steps to check or reproduce
you can use the sandbox below:
https://codesandbox.io/s/ngx-infinitegrid-demo-gridlayout-9m3yw?file=/src/app/app.component.html

1) click on the red button
2) scroll up back to top

all items above the containing group will change direction as shown below
Before:
![image](https://user-images.githubusercontent.com/11808840/80923047-bda58a00-8d89-11ea-80e7-ca9f275a0421.png)

After:
![image](https://user-images.githubusercontent.com/11808840/80923059-d4e47780-8d89-11ea-8135-788cde32e765.png)

For me it seems that the order is totally reversed before the item that we moved to

**Comment by daybrush** [comment]
@msqaddura 

Thank you for bug reporting.
I'll fix it and release soon.

**Comment by daybrush** [comment]
@msqaddura 

`@egjs/ngx-infinitegrid` 3.0.5 is released. Thank you
