### ISSUE TITLE
React: Cannot read property 'tagName' of undefined

### ISSUE THREAD

**Issue by adsee42** [naver/egjs-infinitegrid#340]
## Description

https://codesandbox.io/s/eidk8

I think this is the official example for React.
I didn't change anything.
It shows this error when page opened.

Only error when using `loading` property.
If I comment the line `// loading={<div className="loading">Loading...</div>}`, no error but also no loading component shown.

**Comment by daybrush** [comment]
@adsee42 

Oh. Thank you. I'll fix it soon.

**Comment by daybrush** [comment]
@adsee42 

`react-infinitegrid` 3.0.5 is released. Check it again.

**Comment by adsee42** [comment]
It worked! Thank you!
