### ISSUE TITLE
Initial layout shows only one column

### ISSUE THREAD

**Issue by adsee42** [naver/egjs-infinitegrid#341]
## Description

I'm using `react-infinitegrid` with `material-ui`.

When the page is opened, `GridLayout` shows only one row with initial images stacking together (see images below)

![image](https://user-images.githubusercontent.com/54787881/83397952-6acafb00-a439-11ea-8a4a-99b5b0008d10.png)
![image](https://user-images.githubusercontent.com/54787881/83397992-7e766180-a439-11ea-9aa7-441ad4b29fcb.png)

After changing the window size by dragging the browser frame, the images show as expected.

![image](https://user-images.githubusercontent.com/54787881/83398363-2d1aa200-a43a-11ea-8f89-8af751124ebd.png)

Any idea why is this happening?

**Comment by daybrush** [comment]
@adsee42 


I want to know how you use infinitegrid.

Any test or sample code?

**Comment by daybrush** [comment]
@adsee42 

I think it is similar to this issue, but I think it will be solved together if this problem is solved.

https://github.com/naver/egjs-infinitegrid/issues/340

**Comment by adsee42** [comment]
@daybrush
 
Thank you!
I would love to show some code, but infinitegrid was pretty deep inside the code structure that produced the problem and I don't how make a SIMPLE code to reproduce this. sry...

In fact another page with similar code structure worked great; the only difference is that,
in the above code with problem, I split the infinitegrid into another js file inside a functional component and referenced it in a class component.
And after I put infinitegrid inside the class component in another file, it worked as expected, no strange layout.

It could be the cause, but I'm not sure without any experiment.
I'll comment here if anything found.

**Comment by adsee42** [comment]
I just noticed similar layout in another page.

The infinitegrid was inside a panel of `react-swipeable-views`.

If I open the page, and change panel to for example tab 2 before the images are loaded from server, and switch back after the images are loaded, all images stacked together, not one column but 3 columns.

According to Chrome dev-tool, the container is full width but only has height `30px`.

So my guess is that when the images are loaded, if the container is not showing, its size is mis-calculated and caused the images' position to be strange and stacked together.

Is there any way to add `width: 100%, height: 100%` to the container?

**Comment by daybrush** [comment]
it's not possible. But if something has changed before the image is loaded, would you like to call `infiniteGrid.layout(true)`?

**Comment by adsee42** [comment]
Sry if it's already documented somewhere, but what is the timing and where to call `.layout(true)`?

From the document, I only found [this example](https://naver.github.io/egjs-infinitegrid/release/latest/doc/eg.InfiniteGrid.html). How could I do this in React?

I tried `const gridRef = React.useRef(null)` with `<GridLayout  ref={gridRef} ...`,
and called `gridRef.current.layout(true)` in `onLayoutComplete`.
Obviously this is the wrong way (caused infinite loop..)

I also tried  `useEffect` and call `gridRef.current.layout(true)` when images changed.
And by `console.log(gridRef)` and calling `layout` in dev-tool console didn't work neither.

So may be `useRef` is not the right to do it in React?

**Comment by daybrush** [comment]
@adsee42 

It is not right to call in onLayoutComplete.

Once that situation is not common. Inside the component, there is code waiting for the image to load.

Was there no image when it was first loaded? It works as if it weren't.

When all images are loaded, layout should be called only once.

**Comment by adsee42** [comment]
`useRef` did not work.

But I managed to avoid this problem by unmount the grid every time swipeable-views goes to other panels.

Now it works perfectly, though reload of images happening every time I switch panel back. (Maybe time to do some cache with `react-query`.)

After the project I'm currently working on is finished, I'll try to make a codesandbox example to see if I can reproduce this.

**Comment by quyctd** [comment]
@adsee42 Hi, could you show me the code to unmount the grid? I have the same problems.

**Comment by adsee42** [comment]
@quyctd 
Nothing complicated here, just use a `switch` and return panel.
Say you have 3 panels, and 3 tabs.
if current tab === 1
return panel1.
That way, I think I unmounted the panel...
If it's not clear, I would paste some code.

**Comment by quyctd** [comment]
@adsee42 Thank you for the sharing.

I realized that my issue happens because of the width of the `GridLayout container` change when list items doing the update. So I fixed this issue by just added `width: 100%` into CSS.
