### ISSUE TITLE
Cookies breaking the app

### ISSUE THREAD

**Issue by msqaddura** [naver/egjs-infinitegrid#351]
## Description
A cookie associated with a cross-site resource at http://naver.github.io/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

![image](https://user-images.githubusercontent.com/11808840/90958091-a73b4f80-e49a-11ea-92b8-b3bbad2ec80d.png)

![image](https://user-images.githubusercontent.com/11808840/90958130-eec1db80-e49a-11ea-8392-9b83c63abbf3.png)

## Steps to check or reproduce
- package : ngx-infinitegrid with angular 10
This happens every now and then, i assume there is an incremental check that after some visits add the tags

**Comment by msqaddura** [comment]
Hi @daybrush,  tagging you as you last pushed to the ngx-infinitegrid package, 
What do you think about the issue, does naver have time to fix it?

Thank you in advance

**Comment by daybrush** [comment]
@msqaddura 

I'm not sure where this is happening. Won't you give me an address?

ngx-infinitegrid pacakge local test?

The only thing that uses cookie is ga.

Other than that, it seems like an image-related warning.

**Comment by msqaddura** [comment]
@daybrush 
Indeed i looked into the code and there is no place where it is used apart from local test
I havent been able to reproduce it again so i assume we can close the ticket for now
