### ISSUE TITLE
Items flicker when resize window

### ISSUE THREAD

**Issue by quyctd** [naver/egjs-infinitegrid#352]
## Description

First of all, I want to thank you for creating this project. It's excellent, especially in terms of performance and documentation. Very easy to use and customize.

I'm using GridLayout with ReactJS, everything OK, but when trying to resize the windows, the items flicker and then re-sort after that, this problem didn't show up in the demos. It looks a little bit unfriendly for the user. Is there any way to work around this problem?

The flicker problem looks precisely like this gif (u can look at the margin between items):
![](https://user-images.githubusercontent.com/3433062/40041387-b98fc9e8-5858-11e8-979a-736126d15310.gif)

**Comment by daybrush** [comment]
@quyctd 

Does the size of the item change depending on the screen size?

Is flickering shaking? Or does it disappear and appear?

Didn't you give me a demo address where I can test it?

**Comment by quyctd** [comment]
@daybrush 
Sorry for the late response. 
- Yes, the size of the item change depending on the screen size.
- It is flickering shaking. The bigger margin between items, the flickering shaking when resize windows becomes more visible.
Here is a demo sandbox, you can test here: https://codesandbox.io/s/gifted-star-6wu58

**Comment by daybrush** [comment]
@quyctd 

We debounce the resize event on the infinitegrid. So it seems that such a phenomenon appears. Let's discuss the debounce option.

**Comment by quyctd** [comment]
As I understand, you are using the debounce time to avoid Egjs re-layout continuously. So if we reduce the time of the debounce time, it can affect performance or happen some unexpected new bugs, right?

I have an idea but not sure if it will be good.

When the resizing event starts, we fix the width of the `masonry container` to be equal to the width before resizing, and when the resize event ends, we update the with of the `masonry container` again and start reordering the layout.

**Comment by daybrush** [comment]
@quyctd 

`@egjs/infinitegrid` 3.7.0 is released.
`resizeDebounce`, `maxResizeDebounce` options are added.

Use it.

**Comment by quyctd** [comment]
Thank you, it's work :100:
