### ISSUE TITLE
Cards with lazy loading images

### ISSUE THREAD

**Issue by cloewen8** [naver/egjs-infinitegrid#354]
## Description
If an element is appended that includes an `img` with the `loading="lazy"` attribute. All cards will fail to be laid out. Optimally these elements should be appended and positioned as if they did not have the image (optionally with the width and height applied ahead of time), then re-positioned when the image loads at a later point.

## Steps to check or reproduce
This can be reproduced using any grid with images:
1. Navigate to https://codepen.io/pen/?&editable=true=https%3A%2F%2Fnaver.github.io%2Fegjs-infinitegrid%2Fassets%2Fhtml%2Fgrid.html
2. In the JS section, change (line 1)
```js
var template = '<div class="item"><div class="thumbnail"><img src="${link}../../assets/image/${no}.jpg"></div><div class="info">${text}</div></div>';
```
to (adding `loading="lazy"`)
```js
var template = '<div class="item"><div class="thumbnail"><img loading="lazy" src="${link}../../assets/image/${no}.jpg"></div><div class="info">${text}</div></div>';
```

**Comment by daybrush** [comment]
@cloewen8 

Thank you. Native image lazy loading has not yet been applied. We will add it later.

**Comment by cloewen8** [comment]
No updates, but also not resolved. Just patient waiting here.

**Comment by daybrush** [comment]
@cloewen8 

Sorry for the long wait. I am going to start working. I plan to release it with another PR.

**Comment by cloewen8** [comment]
No worries. I consider lazy loading to be more of a nicity then a requirement.

**Comment by daybrush** [comment]
@cloewen8 

`@egjs/infinitegrid` 3.7.0 is released. Try it.

**Comment by cloewen8** [comment]
Works on my machine. I have it queued up to test on a production website later tonight, I'll let you know if I encounter any problems.

**Comment by cloewen8** [comment]
Works great!
