### ISSUE TITLE
Preact: Cannot read property 'tagName' of undefined

### ISSUE THREAD

**Issue by hayleybrooks** [naver/egjs-infinitegrid#356]
## Description

I am trying to use your React package for InfiniteGrid in Preact. I encounter the `Cannot read property 'tagName' of undefined` error upon scrolling to the bottom of the grid when using (what I think is) your official React demo code:

https://codesandbox.io/s/eidk8

The latest version of Preact comes with compatibility for all of the React ecosystem (and I use other packages for React without issue). I know this may be outside of what you want to support, but I would be super grateful if it is a quick fix!

## Steps to check or reproduce

Here is a demo using the exact code from the demo above but in Preact:

https://codesandbox.io/s/nervous-shape-iboin

**Comment by daybrush** [comment]
@hayleybrooks 

I think it is a problem that occurs because react and preact are different.


in react, componentDidUpdate => update state callback
in preact, update state callback => componentDidUpdate

I wanted it to behave like react, but it doesn't seem to be. I will fix it later.

**Comment by hayleybrooks** [comment]
@daybrush ahh got it, I figured it was some lifecycle difference between the two frameworks. Thanks so much for looking into it! I'm really excited to use this fantastic library.

**Comment by daybrush** [comment]
@hayleybrooks 

react-infinitegrid@3.0.6 is released.

Check it again.

Thank you :)
