### ISSUE TITLE
Event append is called before the previous finished

### ISSUE THREAD

**Issue by literakl** [naver/egjs-infinitegrid#365]
## Description
I use the latest Vue port. I realized that my REST backend is called three times with the same parameters. Here is the SO question: https://stackoverflow.com/questions/64731992/infinitegrid-duplicates-api-calls

I tried to reproduce the scenerio in codesandbox. I simplified the code and I do not have the same API calls now but I can reproduce that the `append ` event is called before the previous call is finished when I use long running async method. When I switch to sync variant, everything runs smoothly.

## Steps to check or reproduce

https://codesandbox.io/s/charming-cache-w56p2?file=/src/components/HelloWorld.vue:1748-1756

```
    loadAsync(marker) {
      const method = this.loadSync;
      return new Promise(function (resolve, reject) {
        setTimeout(function () {
          resolve(method(marker));
        }, 3000);
      });
    },
    async onAppend({ groupKey, startLoading }) {
      const marker = this.index;
      this.index += 1;
      console.log(`onAppend thread = ${marker} group key = ${groupKey}`);
      const { list } = this;
      if (this.isEnded) return;
      console.log(`loadItems thread = ${marker} start = ${this.start}`);
      let items = await this.loadAsync(marker);
      // let items = this.loadSync(marker);
      this.start = this.start + items.length;
      if (items.length === 0 || this.start > 20) {
        console.log(`loadItems thread = ${marker} no data`);
        this.isEnded = true;
        this.$refs.ig.endLoading();
      }
      console.log(`loadItems thread = ${marker} processed`);
      startLoading();
      this.list = list.concat(items);
      console.log(`loadItems thread = ${marker} finished`);
    },
    onLayoutComplete({ isLayout, endLoading }) {
      console.log(`onLayoutComplete isLayout = ${isLayout}`);
      if (!isLayout) {
        endLoading();
      }
    },
```

If you look closely you can see that thread 7 called `this.$refs.ig.endLoading();` so it should be the last iteration but there are two `append` event emitted anyway. Why? It seems to me like a bug.

I do not get the group key purpose as it is always empty. I did not get it from the documentation. Is this proper behaviour?

```
onAppend thread = 1 group key = 
loadItems thread = 1 start = 0
loadItems thread = 1 processed
loadItems thread = 1 finished
onLayoutComplete isLayout = false
onAppend thread = 2 group key =
loadItems thread = 2 start = 3
onAppend thread = 3 group key =
loadItems thread = 3 start = 3
loadItems thread = 2 processed
loadItems thread = 2 finished
loadItems thread = 3 processed
loadItems thread = 3 finished
onLayoutComplete isLayout = false
onAppend thread = 4 group key =
loadItems thread = 4 start = 9
onAppend thread = 5 group key =
loadItems thread = 5 start = 9
loadItems thread = 4 processed
loadItems thread = 4 finished
loadItems thread = 5 processed
loadItems thread = 5 finished
onLayoutComplete isLayout = false
onAppend thread = 6 group key =
loadItems thread = 6 start = 15
onAppend thread = 7 group key =
loadItems thread = 7 start = 15
loadItems thread = 6 processed
loadItems thread = 6 finished
loadItems thread = 7 no data
loadItems thread = 7 processed
loadItems thread = 7 finished
onLayoutComplete isLayout = false
onAppend thread = 8 group key =
onAppend thread = 9 group key =```

**Comment by literakl** [comment]
What is the purpose of startLoading() and endLoading(), please?

**Comment by daybrush** [comment]
https://naver.github.io/egjs-infinitegrid/storybook/?path=/story/loading-bar-with-data-delay--grid-layout

In startLoading and endLoading, the loading bar appears and disappears, and some functions are temporarily disabled (moveTo, useFit).

The append and prepend work and must be prevented through the isProcessing method.

```js
onAppend({ groupKey, startLoading, currentTarget }) {
    if (currentTarget.isProcesing()) {
        return;
    }
}
```

**Comment by literakl** [comment]
Thank you, this fixes my serialization issue.

I have another trouble that makes me crazy. The library loads all 21 items but it displays only 14 of them. I can scroll down and up again and again and they are not displayed. But when I resize the browser the missing items appears. I look into Vue Chrome extension and the items list is complete and GridLayout holds 21 items of the component to be displayed. I really have no clue how to fix it / identify the root cause. Can you please spot a bug in my code? https://github.com/literakl/mezinamiridici/blob/master/spa/src/components/molecules/ItemList.vue

Many thanks

**Comment by daybrush** [comment]
@literakl 
There was a loading issue. Fix it and  Test @egjs/vue-infinitegrid@beta(3.0.4-rc) version

**Comment by literakl** [comment]
thank you!

**Comment by literakl** [comment]
+ @egjs/vue-infinitegrid@3.0.4-rc

restarted the app, there is no change. Has it been merged in this RC?

**Comment by daybrush** [comment]
@literakl 

startLoading is a synchronous function. It should be at the front.

https://codesandbox.io/s/blue-framework-ksh5i?file=/src/components/HelloWorld.vue

**Comment by literakl** [comment]
Wow, what a change! I shall review the documentation if it is covered. I
was confused when I was reading. I missed a lifecycle diagram like Vue has:
https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram. There are many
events and methods but their description did not glue them together to
provide a big picture.

Thank you for amazing help

**Comment by literakl** [comment]
Hi, I found that displaing the further items does not work on some screen sizes. 

  "dependencies": {
    "@egjs/vue-infinitegrid": "^3.0.4-rc",


InfiniteGrid.ts #render

```
visibleChildren = nativeIG.getRenderingItems().map(item => item.vnode);
if (this.$slots.loading) {
  visibleChildren.push(...this.$slots.loading);
}
```

I can reload the page and try to scroll down many times without luck. If I resize the screen, the remaining elements appear immediatelly.

![image](https://user-images.githubusercontent.com/6383287/98990796-3c466580-252b-11eb-8155-ac5bbaa883da.png)

This dimension works each time I reload the page:

![image](https://user-images.githubusercontent.com/6383287/98990878-5c762480-252b-11eb-8eba-5c90900527e3.png)

**Comment by daybrush** [comment]
Could I ever test that page?

**Comment by literakl** [comment]
You can download the source code and run it locally. I can provide you my database export. You need NodeJS and MongoDB. If you do not have Mongo, I can upload data to Mongo Atlas cloud.

**Comment by daybrush** [comment]
@literakl 

Test this code.
1. add isProcessing
2. isEnded The check point is brought forward.
3.  endLoading was done only when items.length is 0.
```js
async onAppend({ groupKey, startLoading }) {
      const marker = this.index, start = this.start || 0, { tag } = this;
      const newGroupKey = parseFloat(groupKey || 0) + 1;

      if (this.$refs.ig.isProcessing()) {
        return;
      }
      this.$log.debug(`loadItems ${marker} Start = ${start}`);

      if (this.isEnded) {
        this.$log.debug(`loadItems ${marker} End detected`);
        return;
      }
      startLoading();
      this.index += 1;
      this.start = start + this.pageSize;

      let items = await this.$store.dispatch('GET_ITEM_STREAM', { start, size: this.pageSize, tag });

      if (items.length === 0 || items.length < this.pageSize) {
        this.$log.debug(`loadItems ${marker} End of data`, items);
        this.isEnded = true;
        if (items.length === 0) {
          this.$refs.ig.endLoading();
          return;
        }
      }

      // this.start = start + items.length;
      if (this.exceptItem) {
        items = items.filter(item => item._id !== this.exceptItem._id);
      }
      items.forEach((item) => { item.groupKey = newGroupKey; });
      this.$log.debug(`loadItems ${marker} Data ready, call startLoading`);

      this.list = this.list.concat(items);
      this.$log.debug(`loadItems ${marker} Finished`);
    },
```

**Comment by literakl** [comment]
Thank you for your patience. I ordered a virtual server and started the setup. Once ready I will post a link here. 
latest Chrome, Windows 64, mouse

Dataset has 23 items, one is skipped (removed by filter)

1500, 1521, 1587, 1740 pixels - 4 items per row, only 8 items displayed
1454 pixes, 4 items per row, 22 items displayed
1274, 1173, 1057 pixels, 3 items per row, 22 items displayed

**Comment by daybrush** [comment]
Thank you. I'll check again when you're ready.

**Comment by literakl** [comment]
I made it and I am able to reproduce it here: https://beta.mezinamiridici.cz/

I am simulating different page sizes via Chrome develop tools. Data is incomplete for some sizes but when I change page width the rest of data is displayed immediatelly. I can reload the page many times for some widths but the trouble persists.

This picture is for 150 width.
![image](https://user-images.githubusercontent.com/6383287/99399421-ee907b00-28e5-11eb-9477-685c62570692.png)

**Comment by daybrush** [comment]
@literakl 
![스크린샷 2020-11-18 오후 1 53 23](https://user-images.githubusercontent.com/3433062/99485272-7ee1c500-29a5-11eb-8ea1-e05dea92f366.png)

The height of that placeholder area becomes 530px.

![스크린샷 2020-11-18 오후 1 54 41](https://user-images.githubusercontent.com/3433062/99485374-ad5fa000-29a5-11eb-91c0-43705e19594f.png)
Actually, it is about 320px.


 It seems that the vue-infinitegrid is miscalculating the area as 530px.


If you know when the placeholder is removed, call ig.layout().

**Comment by literakl** [comment]
Wow! I removed that placeholder and it started to work! Thank you very much!
