### ISSUE TITLE
One item per line layout

### ISSUE THREAD

**Issue by literakl** [naver/egjs-infinitegrid#369]
## Description
I use Grid layout to position the item boxes as infinite stream already. I have a second use case for infinite dynamic loading of data but its intended presentation will vary. Here is plain old list of links. GridLayout does not fit there and no other layout does. How can I position one item per line?

## Steps to check or reproduce

https://codesandbox.io/s/flamboyant-poincare-3j97x?file=/src/components/HelloWorld.vue

```
  <GridLayout
    ref="ig"
    :options="options"
    :layoutOptions="layoutOptions"
    @append="onAppend"
    @layout-complete="onLayoutComplete"
  >
    <div v-for="item in list" :key="item._id" :groupKey="item.groupKey">
      {{ item.caption }}
    </div>
  </GridLayout>
```

StackOverflow question with a screenshot:

https://stackoverflow.com/questions/65161537/one-item-per-line-in-infinitegrid

**Comment by daybrush** [comment]
@literakl 

How about making the width of the item 100%?

**Comment by literakl** [comment]
I have decided to remove infinitegrid for this functionality and implement
a button Load more.

út 8. 12. 2020 v 3:25 odesílatel Daybrush (Younkue Choi) <
notifications@github.com> napsal:

**Comment by daybrush** [comment]
@literakl 

If you need anything later, please feel free to write issue.

Thank you :)

**Comment by literakl** [comment]
Thanks
