### ISSUE TITLE
Item orders is not maintained

### ISSUE THREAD

**Issue by literakl** [naver/egjs-infinitegrid#370]
## Description

Some items are displayed later than other items that were streamed earlier. My items display date so it is evident that the order is no preserved. It may be a placement optimization that depends on the the box size, but it looks like a bug.

![image](https://user-images.githubusercontent.com/6383287/102241487-504e0000-3ef9-11eb-9c91-5929d9177824.png)

## Steps to check or reproduce

See https://beta.mezinamiridici.cz/ and watch /api/v1/item-stream response for data passed from backend

https://github.com/literakl/mezinamiridici/blob/master/spa/src/components/organisms/ItemList.vue

**Comment by daybrush** [comment]
@literakl 

```
13.12, 13.12, 13.12, 12.12
12.12, 11.12, 11.12, 9.12, 10.12
```

GridLayout is a masonry layout with brickwork. From the lower part, stack up like Tetris.

So it is a normal working. A similar UI, pinterest, does the same.
