### ISSUE TITLE
Responsive for JustifiedLayout

### ISSUE THREAD

**Issue by quyctd** [naver/egjs-infinitegrid#371]
## Description

I'm using `JustifiedLayout` to display images. But do we have any options that can make it responsive? For example:
- 3 columns per row on desktop
- 2 columns per row on tablet
- 1 column per row on mobile

## Steps to check or reproduce

Your own sandbox code is not responsive yet: https://codesandbox.io/s/5w7vrr0kwk

**Comment by daybrush** [comment]
@quyctd 

Oh, sorry. No dynamic options are available yet. We still have to access and use private variables.

See demo:
https://codesandbox.io/s/react-infinitegrid-justifiedlayout-demo-forked-lm112?file=/src/index.tsx

**Comment by quyctd** [comment]
@daybrush Thank you for your confirmation :+1: It'll be greater if you create dynamic options :smile:

**Comment by quyctd** [comment]
I'll close this issue as you have confirmed
