### ISSUE TITLE
React - Infinite Grid Layout - Bad Position On Load More with 1 column

### ISSUE THREAD

**Issue by ThomasSertorio** [naver/egjs-infinitegrid#393]
## Description
I use the Infinite Grid Layout in desktop with no problem, everything works fine 👌. Actually everything works fine as long as the layout fits at least 2 columns.
![two_columns_no_problems](https://user-images.githubusercontent.com/12392239/114581651-2d9ddf00-9c80-11eb-8a39-5a433eb113b5.gif)

But when my layout switches to one column, newly added items are not correctly positioned: the initial load works fine but then when scrolling new items are added at left: -100000px; top: -100000px; positions 👇 
![one_column_problem](https://user-images.githubusercontent.com/12392239/114582032-853c4a80-9c80-11eb-973a-92b0ed9963ce.gif)

## Steps to check or reproduce
Code is really simple 👇 
```javascript
const Publications = ({ reportPublications, fetch, fetchMore, loading }) => {
  const { t } = useTranslation('publicationsTab')

  useEffect(() => {
    if (!reportPublications) {
      fetch({ first: ITEMS_PER_PAGE })
    }
  }, [fetch, reportPublications])

  const publications = reportPublications?.edges?.map((edge) => edge.node.publication)
  const pageInfo = reportPublications?.pageInfo

  const onAppend = () => {
    pageInfo.hasNextPage && fetchMore({variables: { after: pageInfo.endCursor }})
  }

  const isLoading = (loading || (reportPublications === undefined))

  return (
    <Container>
      <Header>
        {isLoading ?
          <span><SpinnedLoader /></span>
          :
          <span>{ t('publications', {count: reportPublications.totalCount || 0}) }</span>
        }

      </Header>
      {(isLoading) ?
        <LoadingGrid>
          { Array.from(Array(8).keys()).map((i) => <Publication publication={{loading: true}} key={i}/>) }
        </LoadingGrid>
        :
        <GridLayout
          tag = "div"
          options={{ transitionDuration: .3, isConstantSize: true }}
          layoutOptions={{ margin: 24, align: 'justify' }}
          onAppend={onAppend}
        >
          {publications.map((publication, i) => {
            return <Publication publication={publication} key={publication.id}/>
          })}
        </GridLayout>
      }
    </Container>
  )
}

export default Publications
```
When I check the DOM, I can see the new items, they do have a different keys, just bad position.

Is there anything I miss ?

**Comment by daybrush** [comment]
@ThomasSertorio 

I have found a similar problem.

We're fixing the problem, but there are a few things to check.

Is there a blank img src for lazy loading?

**Comment by ThomasSertorio** [comment]
@daybrush you mean an img src that don't resolve ?

No there's not. In "real life" I may have issue with not resolving img src but for the purpose of the issue, I have tested and retested with resolving images (https://dummyimage.com/1080x1080/DFDFFA). So no problem with blank image if it's what you meant.

**Comment by daybrush** [comment]
@ThomasSertorio 

Is there any test address where I can test the situation?

**Comment by ThomasSertorio** [comment]
@daybrush 

I've just email you an access to a review app. I can also screen aynthing you want here.

**Comment by daybrush** [comment]
@ThomasSertorio 

Oh Thank you :) i checked.
Would you like to update react-infinitegrid version? I think I can solve this problem.

**Comment by ThomasSertorio** [comment]
@daybrush splendid !
Upgrading to `3.2.3` did the job.
Thank you for your time.
