### ISSUE TITLE
Doc issue - missing changelog

### ISSUE THREAD

**Issue by literakl** [naver/egjs-infinitegrid#394]
## Description
I have upgraded vue-infinitegrid and I want to know what has changed in the previous releases.

- there is no easy to find a relation between vue and inifinitegrid releases. E.g. vue 3.2.3 bundles "@egjs/infinitegrid": "~3.8.2". This can be found after the installation in node_modules directory.
- https://naver.github.io/egjs-infinitegrid/ has no changelog for developers.
- https://github.com/naver/egjs-infinitegrid/releases is much hard to use than for example https://bootstrap-vue.org/docs/reference/changelog

## Steps to check or reproduce
N/A

Thanks for a consideration

**Comment by daybrush** [comment]
@literakl 

Thank you. How about doing this?
https://github.com/naver/egjs-infinitegrid/releases/tag/3.8.2

**Comment by literakl** [comment]
Great, thanks
