### ISSUE TITLE
Question: Is it possible to manually trigger onAppend?

### ISSUE THREAD

**Issue by droplab** [naver/egjs-infinitegrid#396]
## Description
My use case is a bit odd, so here it goes... I want to use the default scroll behaviour to trigger the first 3 pages of content but then after that, only trigger new content manually (via a button click).

I realize i could probably disable the scroll triggering by setting threshold to a negative number but am curious what you recommend for manually triggering the onAppend callback?

Thanks very much!

**Comment by daybrush** [comment]
@droplab 

I'm sorry. There is no way to manually call onAppend.
In the framework, you have to add the list yourself.

In the case of vanilla, you have to call the append method.
