### ISSUE TITLE
Append breaks after resize up

### ISSUE THREAD

**Issue by v1ack** [naver/egjs-infinitegrid#399]
## Description
Append breaks after changing window height bigger. Is's floating bug, it doesn't happen every time

Actual for all layouts except grid

## Steps to check or reproduce
1. Open https://naver.github.io/egjs-infinitegrid/storybook/?path=/story/virtual-scroll--frame-layout
2. Make window height lower
3. Scroll down
4. Make window height bigger than it was in point 2
5. Scroll down

https://user-images.githubusercontent.com/11501957/118737681-0e313d80-b84e-11eb-8a76-3cd8463c924a.mp4

**Comment by daybrush** [comment]
@v1ack 

InfiniteGrid checks whether the next group is added according to the scroll event.

In my opinion, it's likely a browser issue.

**Comment by daybrush** [comment]
@v1ack 
Can you know the name of the browser you are using?

**Comment by v1ack** [comment]
It is chromium-based (yandex), but i face this issue in firefox too

**Comment by daybrush** [comment]
@v1ack 

Thank you. I found the problem and will fix it soon.

**Comment by daybrush** [comment]
@v1ack 
* `@egjs/infinitegrid` 3.8.3
* `@egjs/ngx-infinitegrid` 3.2.4
* `@egjs/react-infinitegrid` 3.2.4
* `@egjs/vue-infinitegrid` 3.2.4
* `@egjs/svelte-infinitegrid` 3.2.4

infinitegrid's new version is released. The demo was also fixed.
