### ISSUE TITLE
Is it possible to have certain element to be in 2 column?

### ISSUE THREAD

**Issue by framelita** [naver/egjs-infinitegrid#407]
I tried using GridLayout and set certain elements to have wider width, but it kept showing as the same width as others.

Below is an example if I'm using Masonry
![sample](https://user-images.githubusercontent.com/5145692/124206292-a3924380-db15-11eb-983b-89b3a71114cf.jpg)

Below is an example if I'm using GridLayout
![sample2](https://user-images.githubusercontent.com/5145692/124206784-988be300-db16-11eb-9eda-65aff7536e36.jpg)

here is a codepen https://codepen.io/framelita/pen/oNWXEXy

**Comment by daybrush** [comment]
@framelita 

https://github.com/naver/egjs-grid

Based on @egjs/grid, we will support this feature in 4.0.

But as a result of testing, there are still bugs. I'll fix the bug and let you know

**Comment by daybrush** [comment]
@framelita 

This is an example using grid.
https://codepen.io/daybrush/pen/poPbQRg

**Comment by framelita** [comment]
Nice! Thank you! :)
