### ISSUE TITLE
Incompatibility of @egjs/ngx-infinitegrid (v3.2.5) with @egjs/ngx-flicking (v4.1.1)

### ISSUE THREAD

**Issue by GitHubish** [naver/egjs-infinitegrid#408]
When I add the two dependencies, it "breaks" `@egjs/ngx-flicking` because the `types.d.ts` file present in `node_modules\@egjs\component\declaration` is deleted by `@egjs/ngx-infinitegrid` (v3.2.5). Can you please fix the problem?

**Comment by daybrush** [comment]
@GitHubish 

Would you like to check if it works with `npm ci`? It seems that node_modules is not properly updated.

If that doesn't work, We'll have to update all @egjs/component.

**Comment by daybrush** [comment]
@GitHubish 

Although flicking uses version 3 components, dependency modules (axes, imready) use version 2 components. Perhaps it would be better to reinstall the node modules.
