### ISSUE TITLE
"container: true" not working in vue-infinitegrid v4 upgrade

### ISSUE THREAD

**Issue by paul-park-dematic** [naver/egjs-infinitegrid#422]
## Description

Versions:

- "@egjs/infinitegrid": "4.0.0",
- "@egjs/vue-infinitegrid": "4.0.0",

Using [grid option "container"](https://naver.github.io/egjs-infinitegrid/docs/api/MasonryInfiniteGridOptions/) does not render children.

Modifying `@egjs/vue-infinitegrid/dist/infinitegrid.esm.js` seems to fix the issue:

```
  methods.$_renderContainer = function (h) {
    var props = this.$props;
    var visibleChildren = this.$_getVisibleChildren();
    var container = props.container; // eslint-disable-next-line @typescript-eslint/no-unused-vars

    var containerTag = props.containerTag || "div";

    if (container) { // when container is set to boolean true, this did not pass `(container === true)`

// this should return an array
      return [h(containerTag, {
        ref: "containerRef"
      }, visibleChildren)];
    }
    return visibleChildren;       // returns array of children
  };

```

I assume the fix should be somewhere in: `@egjs/vue-infinitegrid/src/InfiniteGrid.ts`

**Comment by daybrush** [comment]
@paul-park-dematic 

Oh, Thank you. I'll fix it soon.

**Comment by daybrush** [comment]
@paul-park-dematic 

vue-infinitegrid 4.0.1 is released. Check it again.

**Comment by paul-park-dematic** [comment]
@daybrush works now thank you
