### ISSUE TITLE
The VUE3 code I copied from the official website doesn't seem to work properly

### ISSUE THREAD

**Issue by StarEyeser** [naver/egjs-infinitegrid#447]
## Description
It always prompts
··Property "$scopedSlots" was accessed during render but is not defined on instance.
I read the document, but I still can't solve it. So I want to ask for your help.

## Steps to check or reproduce
<template>
  <masonry-infinite-grid
      class="container"
      v-bind:gap="5"
      @request-append="onRequestAppend"
  >

    <div
        class="item"
        v-for="item in items"
        :key="item.key"
        :data-grid-groupkey="item.groupKey"
    >
      <div class="thumbnail">
        <img
            v-bind:src="
            'https://naver.github.io/egjs-infinitegrid/assets/image/' +
            ((item.key % 33) + 1) +
            '.jpg'
          "
            alt="egjs"
        />
      </div>
      <div class="info">egjs {{ item.key }}</div>
    </div>
  </masonry-infinite-grid>
</template>

<script setup lang="ts">
import {MasonryInfiniteGrid} from "@egjs/vue3-infinitegrid"
import {reactive} from "vue";
let items = reactive([])
items = getItems(0, 10)
function getItems(nextGroupKey: number, count: number) {
  const nextItems: any[] = [];

  for (let i = 0; i < count; ++i) {
    const nextKey = nextGroupKey * count + i;

    nextItems.push({ groupKey: nextGroupKey, key: nextKey });
  }
  return nextItems;
}

function onRequestAppend(e) {
  console.log("123")
  const nextGroupKey = (+e.groupKey! || 0) + 1;

  items = [...items, ...getItems(nextGroupKey, 10)];
}
</script>
![屏幕截图 2021-12-02 101400](https://user-images.githubusercontent.com/87892424/144345701-2c17184a-1b9d-4b12-804b-5f0d484daeed.png)

**Comment by daybrush** [comment]
@StarEyeser 

I will check and fix it.

**Comment by daybrush** [comment]
@StarEyeser 

Test `@egjs/vue3-infinitegrid@4.1.3-beta.0`(`@beta`). Thank you :)

**Comment by StarEyeser** [comment]
@daybrush I've tested it. Version @egjs/vue3-infinitegrid@4.1.3-beta.0 works normally. Thank you very much.

**Comment by MeikelLP** [comment]
Still happening for me:
```
[Vue warn]: Property "$scopedSlots" was accessed during render but is not defined on instance. 
  at <MasonryGrid class="columns is-multiline" gap=5 onRequestAppend=fn<bound infiniteHandler> > 
  at <Home onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView key=1 > 
  at <App>
```

Using `^4.1.3-beta.0` 

Template (truncated)
```vue
<masonry-infinite-grid
      class="columns is-multiline"
      v-bind:gap="5"
      @requestAppend="infiniteHandler"
    >
  <shop-item :item="item" v-for="item in items" :key="item.id" :data-grid-groupkey="item.groupKey" class="column is-2"></shop-item>
</masonry-infinite-grid>
```

Handler
```js
async infiniteHandler (e) {
      this.page++
      const newItems = await this.getItems()
      this.items.push(...newItems)
}
```
