### ISSUE TITLE
Sveltekit/TS, "500: Import not found: default" - config issue?

### ISSUE THREAD

**Issue by nimmolo** [naver/egjs-infinitegrid#455]
Do i need to change something in my config to use InfiniteGrid with Sveltekit and Typescript? I'm getting this error importing `MasonryInfiniteGrid` into my layout. 

Error message in dev is `500: import not found: default`

Error message in build is `'default' is not exported by node_modules/.pnpm/@egjs+svelte-infinitegrid@4.1.1/node_modules/@egjs/svelte-infinitegrid/src/index.js, imported by src/routes/observations/index.svelte`

However, Typescript/ESlint seems to recognize the export type of `MasonryInfiniteGrid` when i hover.
`(alias) class MasonryInfiniteGrid<T extends GridOptions>
import MasonryInfiniteGrid`

I just reinstalled InfiniteGrid with pnpm, and my package.json is like this:
```json
{
  "name": "project-name",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev --port 3001",
    "etc": "other-scripts"
  }
  "devDependencies": {
    "@apollo/client": "^3.5.4",
    "other-dev-dependencies": "^1.2.3"
  }
  "type": "module",
  "dependencies": {
    "@egjs/svelte-infinitegrid": "^4.1.1",
    "other-dependencies": "^1.2.3"
}
```

Here is the component:
```svelte
<script lang="ts">
  import Item from '$lib/components/observation/Item.svelte';
  import Filter from '$lib/components/observation/Filter.svelte';
  import MasonryInfiniteGrid from '@egjs/svelte-infinitegrid';
  import { onMount } from 'svelte';
  let filter, pageInfo, items;
</script>
...
<MasonryInfiniteGrid
  class="grid"
  gap={5}
  {items}
  on:requestAppend={({ detail: e }) => {
  ...
>
```
If I import from the file in `/grids/` directly, I still get the error:
```svelte
  import MasonryInfiniteGrid from '@egjs/svelte-infinitegrid/src/grids/MasonryInfiniteGrid';
```

**Comment by daybrush** [comment]
@nimmolo 

Use this exports type.
```js
import { MasonryInfiniteGrid }  from '@egjs/svelte-infinitegrid';
```

**Comment by nimmolo** [comment]
Hi @daybrush thanks, I tried that too. TS/eslint also complains about `import { MasonryInfiniteGrid }  from '@egjs/svelte-infinitegrid';`

`Module '"@egjs/svelte-infinitegrid"' has no exported member 'MasonryInfiniteGrid'. Did you mean to use 'import MasonryInfiniteGrid from "@egjs/svelte-infinitegrid"' instead?ts(2614)`

I noticed that unlike this repo, my install does not have `MasonryInfiniteGrid.ts` files in the `@egjs/svelte-infinitegrid/src/grids` folder, I have `MasonryInfiniteGrid.js` files. Did I install correctly?

**Comment by daybrush** [comment]
@nimmolo 

Oh, Sorry. The type was defined incorrectly.
Test `@egjs/svelte-infinitegrid@4.1.2-beta.0`

**Comment by nimmolo** [comment]
Thanks! @daybrush - I will try after the holiday, i'm not at my work computer this week. Will reply as soon as im back. 

Its ok to use pnpm to install it?

**Comment by daybrush** [comment]
@nimmolo 

pnpm should be fine.

**Comment by nimmolo** [comment]
@daybrush Thank you!! Your new beta version fixed the import error.
