### ISSUE TITLE
export 'GridLayout' (imported as 'GridLayout') was not found in '@egjs/react-infinitegrid'

### ISSUE THREAD

**Issue by code-masala** [naver/egjs-infinitegrid#456]
@daybrush 
When i bump @egjs/react-infinitegrid from 1.6.5 to 4.1.1 
This error occure.
Can you help me to figure out the issue

**Comment by daybrush** [comment]
@code-masala 

The name and usage have been changed.

* GridLayout to MasonryInfiniteGrid
* 
Please refer to the following link
https://naver.github.io/egjs-infinitegrid/Guides#masonryinfinitegrid

**Comment by code-masala** [comment]
<MasonryInfiniteGrid
							align="center"
							itemSize={itemWidth}
							isConstantSize={true}
							margin={this.margin}
							transitionDuration={0.3}
							loading={this.showLoadingBar()}
							onAppend={this._onAppend}
							onLayoutComplete={this._onLayoutComplete}
						>
							{listData.map((batch) => {
								return batch.data.map((postHash) => {
									const index = i;
									i++;
									if (i % this.groupThreshold === 0) {
										groupKey++;
									}
									return (
										<VideoFigureListElement
											key={`${postHash}${i}`}
											groupKey={groupKey}
											index={index}
											type={type}
											width={itemWidth}
											postHash={postHash}
											match={match}
											location={location}
										/>
									);
								});
							})}
						</MasonryInfiniteGrid>

**Comment by code-masala** [comment]
can you plz tell me why this is not working?

**Comment by daybrush** [comment]
@code-masala 
 
* onAppend => onRequestAppend
* onLayoutComplete => onRenderComplete
* itemSize => columnSize
* margin => gap
* transitionDuration itemSize are removed

**Comment by code-masala** [comment]
`MasonryInfiniteGrid
							align="center"
							columnSize={itemWidth}
							isConstantSize={true}
							gap={this.margin}
							loading={this.showLoadingBar()}
							onRequestAppend={this._onAppend}
							onRenderComplete={this._onLayoutComplete}
						>
							{listData.map((batch) => {
								return batch.data.map((postHash) => {
									const index = i;
									i++;
									if (i % this.groupThreshold === 0) {
										groupKey++;
									}
									return (
										<VideoFigureListElement
											key={`${postHash}${i}`}
											groupKey={groupKey}
											index={index}
											type={type}
											width={itemWidth}
											postHash={postHash}
											match={match}
											location={location}
										/>
									);
								});
							})}
						</MasonryInfiniteGrid>`

**Comment by code-masala** [comment]
still not working

**Comment by daybrush** [comment]
@code-masala 

Is there an address where I can check the demo or test it out?

**Comment by code-masala** [comment]
```
The above error occurred in the <MasonryInfiniteGrid> component:
    in MasonryInfiniteGrid (created by SwipeHandler)
    in div (created by PullToRefresh)
    in PullToRefresh (created by SwipeHandler)
    in SwipeHandler
    in SwipeHandler (created by VideoFeed)
    in VideoFeed (created by VideoFeedWrapper)
    in VideoFeedWrapper (created by Connect(VideoFeedWrapper))
    in Connect(VideoFeedWrapper) (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by HomeFeedPage)
    in Switch (created by HomeFeedPage)
    in main (created by MainWrapper)
    in MainWrapper (created by HomeFeedPage)
    in div (created by HomeWrapper)
    in HomeWrapper (created by HomeFeedPage)
    in HomeFeedPage (created by HomeFeedPageContainer)
    in HomeFeedPageContainer (created by SigninPrompt)
    in SigninPrompt (created by LanguageComponent)
    in LanguageComponent (created by Connect(LanguageComponent))
    in Connect(LanguageComponent) (created by Connect(Connect(LanguageComponent)))
    in Connect(Connect(LanguageComponent)) (created by Context.Consumer)
    in withRouter(Connect(Connect(LanguageComponent))) (created by Connect(withRouter(Connect(Connect(LanguageComponent)))))
    in Connect(withRouter(Connect(Connect(LanguageComponent)))) (created by HomeFeedPageContainerWrapper)
    in HomeFeedPageContainerWrapper (created by LoadableComponent)
    in LoadableComponent (created by RouteComponent)
    in RouteComponent (created by Connect(RouteComponent))
    in Connect(RouteComponent) (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in App
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider
    in HelmetProvider
```
