### ISSUE TITLE
Sveltekit/TS: "class" property does not exist on type MasonryInfiniteGridOptions?

### ISSUE THREAD

**Issue by nimmolo** [naver/egjs-infinitegrid#459]
## Description
TS/eslint seems to be complaining that the `class` attribute on the `MasonryInfiniteGrid` component is not valid? It's maybe not a big deal but the type might not be defined correctly.
Error message:
```
Type '{ class: string; gap: number; items: any[]; }' is not assignable to type 'IntrinsicAttributes & MasonryInfiniteGridOptions'.
  Property 'class' does not exist on type 'IntrinsicAttributes & MasonryInfiniteGridOptions'.ts(2322)
```
## Steps to check or reproduce
I'm using `class` like this:
```svelte
  <MasonryInfiniteGrid
    class="grid"
    gap={5}
    {items}
    on:requestAppend={({ detail: e }) => {
      e.wait();
      newEdges = handleNext();
      setTimeout(() => {
        e.ready();
        items = [...items, ...newEdges];
      }, 1000);
    }}
    let:visibleItems
  >
```

**Comment by daybrush** [comment]
@nimmolo 

Test @egjs/svelte-infinitegrid@4.1.2-beta.0 version.

Thank you :)

**Comment by nimmolo** [comment]
Thank you @daybrush -- That cleared up the error on `class` attribute.

Now with version `4.1.2-beta.2` i'm getting a type error on `<MasonryInfiniteGrid>` itself 🤔

```
(alias) class MasonryInfiniteGrid
import MasonryInfiniteGrid
Type '{ class: string; gap: number; items: any[]; itemBy: (item: any) => any; }' is not assignable to type 'IntrinsicAttributes & Record<string, any> & SveltInfiniteGridOptions & MasonryInfiniteGridOptions'.
  Property 'status' is missing in type '{ class: string; gap: number; items: any[]; itemBy: (item: any) => any; }' but required in type 'SveltInfiniteGridOptions'.ts(2322)
```

**Comment by nimmolo** [comment]
One more TS note, while you are working on types @daybrush - I know it is a separate issue, i am happy to open separate issue but maybe this is more convenient here. 

For debugging I tried using `let ig;`, `<MasonryInfiniteGrid bind:this={ig}>` and `onMount(() => { console.log(ig.getItems()); });`, but this returns an error: `Uncaught (in promise) TypeError: ig is undefined`. 

Am I declaring the variable `ig` incorrectly?

**Comment by daybrush** [comment]
@nimmolo 

1. Oh Sorry. Try 4.1.3-beta.3 version.
2. it's type issue

```js
let ig!: MasonryInfiniteGrid;
```

**Comment by nimmolo** [comment]
Hi - 
1.  I updated to `4.1.2-beta.3` version, still getting the same error (version `4.1.3-beta.3` did not exist)
2. Ok... maybe it's because i'm loading my items async, and `onMount` is too early

**Comment by daybrush** [comment]
@nimmolo 

Is there a `status` option problem in 4.1.2-beta.3?

**Comment by nimmolo** [comment]
@daybrush sorry i should have been specific. 
There seemed still the `status` problem after updating to beta.3 last night when I wrote that comment. 

But i just restarted VS Code, and the `status` error is now gone. Thanks!
