### ISSUE TITLE
[Angular] Scrolling after new items were received

### ISSUE THREAD

**Issue by ishturmov** [naver/egjs-infinitegrid#469]
## Description
Hi.

Every time, when totally new items are coming to the grid - it's automatically scrolls to the top.
But I have a case when grid is under another component, and when new data came, it's scrolls directly to the top of the page, is it possible to specify element to which it should scroll?

Version 3.2.5

**Comment by daybrush** [comment]
@ishturmov 

Do you have any test demos?

**Comment by ishturmov** [comment]
@daybrush sorry man, issue is not relevant, I found what happens. 
Previous developer was using ngIf directive on grid, and every time when there were no data, grid was hidden and I guess because of it your library was not able element to scroll, and scrolled just to top.
