### ISSUE TITLE
MasonryInfiniteGrid: item remove doesn't work

### ISSUE THREAD

**Issue by minkky** [naver/egjs-infinitegrid#471]
## Description

When I try to delete visibleItems, it seems that the height calculation does not work well.

This is my test code.
https://svelte.dev/repl/7c671ae987cc495dab9e1b50cad90c50?version=3.46.4

When there are 3 items in one line, if you keep deleting the 2nd(0, 1) item, the items at the top are not aligned well.

Is there any possible method to recalculate the height?

Thank you for your consideration.

+)When deleting, only the items within one page(in my case 10 items) seem to be reordered. ~If you keep deleting, the next page(10 items) are sorted and behave the same for each page.~

**Comment by daybrush** [comment]
@minkky 
* `@egjs/infinitegrid` 4.2.0
* `@egjs/ngx-infinitegrid` 4.2.0
* `@egjs/react-infinitegrid` 4.2.0
* `@egjs/vue-infinitegrid` 4.2.0
* `@egjs/vue3-infinitegrid` 4.2.0
* `@egjs/svelte-infinitegrid` 4.2.0

infinitegrid's new version is released. Try it again. Thank you :)

**Comment by minkky** [comment]
@daybrush 

I applied it and confirmed that it works well in the demo.

But I have question about height recalculating.
Is there any way to forcefully recalculate the height?

In my case, most items are pre-loaded and the height is well calculated, but some items are called late and the pre-caclulated height does not fit.
Therefore, the item was deleted based on the initially miscalculated height, so the entire layout seems to be misaligned.

**Comment by daybrush** [comment]
@minkky 

When the container is later resized
```js
<MasonryInfiniteGrid useResizeObserver={true}>...</MasonryInfiniteGrid>
// or
ig.renderItems({ useResize: true });
```

Call the updateItems method to find out the timing when the item's size will change later.
```js
ig.updateItems();
// or resize with container
ig.renderItems({ useResize: true });
```

**Comment by minkky** [comment]
@daybrush 
Thanks. I will try it.

**Comment by igorlanko** [comment]
Hey @daybrush, I'm actually still noticing this issue on `4.11.0` too. Could you please give a hint? I'm listening to a Svelte store with the items change, and calling `renderItems({ useResize: true })`, but after deleting an item the grid is still miffed. Though adding to the store works fine without explicit re-render call!

Here's a REPL: https://svelte.dev/repl/2d45d758814e4b908fc7e19d58895a3e?version=4.2.18.

Thanks!
