### ISSUE TITLE
There are some questions about gap and itemSize

### ISSUE THREAD

**Issue by Sirros** [naver/egjs-infinitegrid#477]
### The following content is from **vue2**

When I try to set the gap property to achieve consistent spacing per column, since I set the width of the items, the spacing per column is not what I want to see. So I tried setting the column property and removing the item's width css property and found that the image would get bigger.

I think when the user sets the column property, the width of each column should be calculated, the user does not need to design the width property for each item. When the window is resized, the size of each column changes accordingly.

So I wonder if my implementation is wrong or the framework doesn't support it?

![image](https://user-images.githubusercontent.com/34034866/165899840-42aa5426-f3cf-4918-af8e-7beb9307a1a7.png)

![image](https://user-images.githubusercontent.com/34034866/165899880-fba272a5-16f2-4c9b-a27a-c30ce1367aa7.png)

![image](https://user-images.githubusercontent.com/34034866/165900178-08a11742-ea80-481f-a429-8275f80d1fd9.png)

![image](https://user-images.githubusercontent.com/34034866/165899545-6139aff9-8ecc-46a8-9fd8-fa96b4a718eb.png)

**Comment by daybrush** [comment]
@Sirros 

Maybe what you're talking about has something to do with `align`. The default value is "justify", and the column spacing can be increased to fill the screen.

If you want to center align, use "center".

Use "stretch" if you want to fill the screen and keep the column spacing as a gap.

**Comment by Sirros** [comment]
@daybrush thanks for the answer~
now I set the number of columns and the align property to stretch, and I found that the layout fails when the window is resized
![image](https://user-images.githubusercontent.com/34034866/166857094-33b55a96-b65d-4190-936b-0bee6f0c04ad.png)
![image](https://user-images.githubusercontent.com/34034866/166857095-8c7e74e0-4b73-4f70-a858-5587865789b6.png)

**Comment by Sirros** [comment]
I found that the layout of the first rendering is also wrong. When I drag the console border, the resize should be triggered, and the layout will be correct at this time.

![image](https://user-images.githubusercontent.com/34034866/166860157-23aaec0a-9a76-47a4-8ed8-98341ee0050b.png)
![image](https://user-images.githubusercontent.com/34034866/166860297-3c9b0202-cf19-4796-84d5-b2872a4640af.png)

**Comment by daybrush** [comment]
@Sirros 

There is a high possibility that the size of the container will change during rendering.

browser. Can I use ResizeObserver?

If so, it is recommended to set the useResizeObserver option to true.

**Comment by Sirros** [comment]
My settings are as follows, still having problems, maybe you can try to verify this problem.
`
align="stretch" 
:gap="20" 
:column="column" 
:useResizeObserver="true" 
`


![image](https://user-images.githubusercontent.com/34034866/167349823-26006f57-420f-4944-aa28-e53fa66a1217.png)

**Comment by Sirros** [comment]
@daybrush 
My settings are as follows, still having problems, maybe you can try to verify this problem.
`
align="stretch" 
:gap="20" 
:column="column" 
:useResizeObserver="true" 
`


![image](https://user-images.githubusercontent.com/34034866/167349823-26006f57-420f-4944-aa28-e53fa66a1217.png)

**Comment by daybrush** [comment]
@Sirros 

Because stretch was used, the height automatically increased as the width increased, but this was not detected.

https://github.com/naver/egjs-infinitegrid/issues/480
The `observeChildren` option will be added in this issue.

**Comment by Sirros** [comment]
@daybrush ok, looking forward~ Thanks for your patience

**Comment by daybrush** [comment]
@Sirros 

InfiniteGrid 4.3.0 is released. use `useResizeObserver` and `observeChildren` to true. Thank you :)

**Comment by Sirros** [comment]
@daybrush thanks for solving
