### ISSUE TITLE
Infinite scroll working in Svelte but not React?

### ISSUE THREAD

**Issue by pozdena** [naver/egjs-infinitegrid#479]
## Description
Items not loading on scroll in React, but working in Svelte.

## Steps to check or reproduce
Infinite scroll is working in this Svelte example:
https://svelte.dev/repl/8c271c4a5c6848eabffd5efe1cc6cfde?version=3.44.2

Essentially the same app does not work in React:
https://codesandbox.io/s/react-repl-forked-foc10i?file=/src/index.js

Can you help me figure out why this isn't working in React? Am I overlooking something? Thank you.

**Comment by daybrush** [comment]
@pozdena 

Since `.container` is a scroll container, you need to set height: 600px to `.container`

https://codesandbox.io/s/react-repl-forked-qhnkcg?file=/src/index.js

**Comment by pozdena** [comment]
@daybrush Thank you!!
