### ISSUE TITLE
Using 'e.remove()' on ContentError causes incorrect behavior

### ISSUE THREAD

**Issue by ruzia** [naver/egjs-infinitegrid#482]
## Description
I am trying to remove 404 images from the grid when using JustifiedInfiniteGrid.
From the API docs I thought I could call 'e.remove()' on the contentError event, but it didn't work.
When I call 'e.remove()', the grid flickers and does not render correctly.

## Steps to check or reproduce
https://codepen.io/ruzia/pen/eYVBQdB

**Comment by daybrush** [comment]
@ruzia 


Thank you :). I'll fix it soon.

**Comment by daybrush** [comment]
@ruzia 

InfiniteGrid 4.3.1 is released. Check it again.

**Comment by ruzia** [comment]
@daybrush Thanks for your quick fix!
It's works nice. 🙌
