### ISSUE TITLE
React MasonryInfiniteGrid not updating when new data is passed in

### ISSUE THREAD

**Issue by astralmedia** [naver/egjs-infinitegrid#487]
## Description

When I pass new data into the array map that displays the items, it keeps the old positioning and does not reflow the layout to the new content...I've tried so much, any ideas?

## Steps to check or reproduce

`return <MasonryInfiniteGrid
        column={columnCount}
        gap={5}
        ref={gridRef}
        loading={<h1>LOAD</h1>}
        onRequestAppend={getNextRequest}
    >
        {_.get(listData, "length", 0) > 0 && listData.map((item, index) => {
            const listTemplate = getTemplate(item, index)
            return listTemplate
        })}
    </MasonryInfiniteGrid>`

**Comment by daybrush** [comment]
@astralmedia 

Even if the size of the item changes, it cannot be easily detected.

Use the useResizeObserver, observeChildren option or

Try calling the updateItems() method.

**Comment by astralmedia** [comment]
That hit the spot! Thank you friend
