### ISSUE TITLE
columnSize invalid

### ISSUE THREAD

**Issue by Sirros** [naver/egjs-infinitegrid#494]
## Description
I want to fit different screen sizes and have the same spacing in each column，but the columnSize invalid

## Steps to check or reproduce
![image](https://user-images.githubusercontent.com/34034866/174938873-6b54622c-ecf5-42fb-833d-593d19933f87.png)
![image](https://user-images.githubusercontent.com/34034866/174938895-8e48a5a9-d8d2-4609-8e8c-39c20c6f6d94.png)

**Comment by daybrush** [comment]
@Sirros 


Thanks for the report. I will fix it soon.

**Comment by daybrush** [comment]
@Sirros 

Sorry but stretch cannot be used with columnSize.
stretch must be used together with the `column` option, and the size is determined by `column`.

**Comment by Sirros** [comment]
@daybrush ok, I also encountered another problem, when I actually use it, there will be an obvious item refresh, Is there any way to fix it?

**Comment by daybrush** [comment]
@Sirros 

What does `refresh` mean?

**Comment by daybrush** [comment]
@Sirros 
I didn't quite understand what you meant, but are you looking for this? `useResizeObserver`, `observeChildren`

https://codesandbox.io/s/jolly-pike-1id91o?file=/src/App.vue

**Comment by Sirros** [comment]
@daybrush Maybe it's an accidental problem, I can't reproduce the problem. If I encounter this problem again, I will try to provide a gif describing the problem.

**Comment by Sirros** [comment]
@daybrush
 I've noticed this happens recently when I'm using it. White blocks appear when the page is scrolled down. Is there any way to optimize this situation？
Also, is it possible to use a transition effect to load each image?

![Image_20220628160951](https://user-images.githubusercontent.com/34034866/176128293-7f6d64e2-34ff-4ba2-9030-096280420ea5.png)
![image](https://user-images.githubusercontent.com/34034866/176128559-a1293c95-19b7-46ed-80a3-0370303931da.png)

**Comment by daybrush** [comment]
@Sirros 


It is most likely because of the loading of the image. Regardless of the loading of the image, if the size can be calculated, it is immediately drawn on the screen.

Perhaps what you want is opacity: 0 to 1?

**Comment by Sirros** [comment]
@daybrush
 ok, If I can get the original length and width of the image, what properties can I set to speed up the rendering of the image?
Yes, would like to have a transition effect of opacity 0 to 1.
 Most of the attribute descriptions in the document have no remarks. I used **useTransform** but it did not take effect.
https://naver.github.io/egjs-infinitegrid/docs/api/MasonryInfiniteGridOptions

**Comment by daybrush** [comment]
@Sirros 

The rendering speed of the image seems impossible. It seems to be an area that varies depending on the performance of the user and the network.

It would be good if examples related to opacity are added to Guides later.

Would you like to check out the demo below? This is a demo of changing the opacity of the mounted item in the renderComplete event.
https://codesandbox.io/s/gracious-waterfall-9k3bsm?file=/src/index.ts:728-735

**Comment by Sirros** [comment]
@daybrush 

I optimize the size of the image and it should speed up the rendering.

ok, i'll take a look. By the way, the renderComplete event of my listening component in vue2 doesn't seem to fire.
`
<masonry-infinite-grid
      v-if="!loading"
      class="container"
      ref="ig"
      align="stretch"
      :gap="20"
      :column="column"
      :useTransform="true"
      :observeChildren="true"
      :useResizeObserver="true"
      @request-append="onRequestAppend"
      @renderComplete="renderComplete"
>
`

**Comment by Sirros** [comment]
@daybrush 

Well, I try to modify the monitored event name @renderComplete to @render-complete and it was fired, my spelling was wrong.

**Comment by Sirros** [comment]
@daybrush 
This happens after adding the transition effect.
![image](https://user-images.githubusercontent.com/34034866/176842035-d2cf48da-c5e8-4a5c-b8b6-c6b9c1ea70b0.png)
![image](https://user-images.githubusercontent.com/34034866/176842055-a884706c-3cb1-4b38-a038-cc08c5893939.png)

**Comment by daybrush** [comment]
@Sirros 

Maybe an image or item with loading="lazy" or data-width or an external lazy loading module?

**Comment by daybrush** [comment]
@Sirros 

Does the same thing happen when I remove the transition effect?

It's not reproducible for me.

Have you ever set limits on CPU and network throttling?

**Comment by Sirros** [comment]
@daybrush 

This doesn't happen when I remove the transition effect.
I used debounce for **onRequestAppend**

`
onRequestAppend: debounce(function (e) {
if (this.loading || this.requesting) {
        return
      }
      e.wait()
      this.getList({ pageNumber: this.requestParams.pageNumber }, 'append')
      e.ready()
}, 80)
`

**Comment by Sirros** [comment]
@daybrush 

After many attempts, The path to reproduce the problem is roughly as follows:
Always scroll the page scroll bar quickly, there is a high probability that the picture has not been loaded but you can continue to scroll down, then the situation in the gif will appear.

![demo](https://user-images.githubusercontent.com/34034866/178485969-d809cfc0-16e5-461e-bd4e-1391d4af204b.gif)

**Comment by daybrush** [comment]
@Sirros 

An error was confirmed.

The error was reproduced when testing in the wheel amount control in Windows.
The error will be fixed soon.

**Comment by daybrush** [comment]
@Sirros 

* `@egjs/infinitegrid` 4.6.0
* `@egjs/react-infinitegrid` 4.6.0
* `@egjs/svelte-infinitegrid` 4.6.0
* `@egjs/vue-infinitegrid` 4.6.0
* `@egjs/vue3-infinitegrid` 4.6.0
* `@egjs/ngx-infinitegrid` 4.6.0

InfiniteGrid's new version is released. Check it again.

**Comment by Sirros** [comment]
@daybrush 
ok, I'll check it when I'm free.
