### ISSUE TITLE
supports the component of framework

### ISSUE THREAD

**Issue by sculove** [naver/egjs-infinitegrid#5]
## Description
consider infinitegrid component for react/angular/vue

**Comment by sculove** [comment]
react https://github.com/naver/egjs-infinitegrid/issues/67

**Comment by N1nJaC0d3** [comment]
what about  Angular7+?

**Comment by younkue** [comment]
@N1nJaC0d3 It will probably run after May or June.

**Comment by N1nJaC0d3** [comment]
> @N1nJaC0d3 It will probably run after May or June.

@younkue Can't wait;  :)

**Comment by NiNJAD3vel0per** [comment]
@daybrush  how is the Angular progress going  ? just curious !

**Comment by jongmoon** [comment]
@NiNJAD3vel0per Sorry. It's planned after June
