### ISSUE TITLE
Import type missing in svelte-infinitegrid

### ISSUE THREAD

**Issue by GrassHopper42** [naver/egjs-infinitegrid#509]
## Description

In svelte-infinitegrid module, `InfiniteGridStatus` type from `@egjs/Infinitegrid` is missing in `SvelteInfiniteGridOptions` interface.

## Steps to check or reproduce

go to `packages/svelte-infinitegrid/src/index.d.ts`.

**Comment by daybrush** [comment]
@GrassHopper42 

* `@egjs/infinitegrid` 4.7.0
* `@egjs/react-infinitegrid` 4.7.0
* `@egjs/svelte-infinitegrid` 4.7.0
* `@egjs/vue-infinitegrid` 4.7.0
* `@egjs/vue3-infinitegrid` 4.7.0
* `@egjs/ngx-infinitegrid` 4.7.0

svelte-infinitegrid' type is fixed. Thank you :)
