### ISSUE TITLE
type not defined for @egjs/react-infinitegrid v4.7.0 ?

### ISSUE THREAD

**Issue by tkmin** [naver/egjs-infinitegrid#516]
## Description

<img width="492" alt="Screen Shot 2022-09-06 at 5 27 47 PM" src="https://user-images.githubusercontent.com/83566566/188586326-3f301362-1176-4158-b035-09c5b82a424a.png">

## Steps to check or reproduce
react version is ^17.0.2

**Comment by Trendymen** [comment]
I had the same problem, there are no generated declaration file in package

**Comment by malangfox** [comment]
Hello @tkmin.

It seems that declarations are missing from our package.
We will release a patch that fixes this issue as soon as possible.

Thank you.

**Comment by tkmin** [comment]
Thank you so mu

> Hello @tkmin.
> 
> It seems that declarations are missing from our package. We will release a patch that fixes this issue as soon as possible.
> 
Thank you so much!

**Comment by malangfox** [comment]
react-infinitegrid 4.7.1 has been released that solves the issues you left.
Please try this version and leave an issue if you encounter any issues.
