### ISSUE TITLE
FrameInfiniteGrid frame property

### ISSUE THREAD

**Issue by asrebo** [naver/egjs-infinitegrid#519]
Can you please explain how array is controling the layout of the elements. From documentation i can`t grasp how to set layout
 
Thanks

**Comment by malangfox** [comment]
Hello @asrebo.

If you are still having problems, this might help.
https://naver.github.io/egjs-infinitegrid/Guides#frameinfinitegrid

An example of this code contains `frame={[[1,1,2,3,3],[1,1,4,4,5]]}` and each frame is arranged as follows.
![grid](https://user-images.githubusercontent.com/13797320/190034781-317ecf06-5119-4b6c-a2d6-81c057d4f24a.jpg)
