### ISSUE TITLE
TypeError with latest sveltekit

### ISSUE THREAD

**Issue by msohaill** [naver/egjs-infinitegrid#528]
## Description
Fails to produce infinite grid. I receive errors with `npm run dev` but not `npm run build`. I get the following error in the browser console:
```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'options.props.GridClass = MasonryInfiniteGrid')
```
This error persists regardless of the type of infinite grid used.

## Steps to check or reproduce
Create sveltekit project with latest. Use [starter code](https://naver.github.io/egjs-infinitegrid/Guides#masonryinfinitegrid). Run `npm run dev`

Sandbox: https://replit.com/@msohaill/test-svelte#src/routes/+page.svelte

Thank you!

**Comment by daybrush** [comment]
@msohaill 

Try @egjs/svelte-infinitegrid@4.9.0-beta.1 version.

Thank you :)

**Comment by msohaill** [comment]
> @msohaill
> 
> Try @egjs/svelte-infinitegrid@4.9.0-beta.1 version.
> 
> Thank you :)

Works like a charm, thank you!

**Comment by msohaill** [comment]
Release 4.9.0 has these changes, so I will resolve this issue.
