### ISSUE TITLE
MasonryInfiniteGrid, not fit it vertically with <Image> Component in NextJS

### ISSUE THREAD

**Issue by holyfrog666** [naver/egjs-infinitegrid#540]
First of all, I'm really thanks for this masonry package.

When I use `<Image>` in NextJS(13.4.3), I have a trouble that masonry layout is not shown what I expected.
All the Images had each variable height and I called them with `<Image>` in `<MasonryInfiniteGrid>.`
and then, Final view show me that masonry layout was not adjusted correctly.
ex) row 2 is not fit it to bottom of row 1 on each images of row 1

When I use `<img>` instead of `<Image>` like above, masonry shows correctly, and the all each image is fit it there own position.

NextJS said I have to use `<Image>` instead of `<img>` and it makes error and warning when I use <img>
( guess it's purpose for SEO. IDK but I wanna use `<Image>`)

**Is there Any way that I can use `<Image>` instead of <img> in NextJS? Please gimme some tips for this, would be appreciate it all**

** I already searched and checked some ways kinda making wrapper above <Image> and added some style css for it, But It was not good. you guys can check that code below.

      // using AutoHeightImage Component
      <AutoHeightImage
        key={ num }
        src={`https://naver.github.io/egjs-infinitegrid/assets/image/${(num % 33) + 1}.jpg`}
        alt="item image"
        loading="lazy"
      />

----------------------------------------------------------------

      // AutoHeightImage Component and styling css
      const AutoHeightImageWrapper = styled.div`
	      width: 100%;
	      & > span {
		      position: unset !important;
		      img {
			      width: 100% !important;
			      height: auto !important;
			      position: relative !important;
			      object-fit: cover;
	          }
	      }
      `;
      
      const AutoHeightImage = ({ ...props }) => {
          console.log(props);
      
          return (
              <AutoHeightImageWrapper>
                  <Image layout="fill" {...props} />
              </AutoHeightImageWrapper>
          );
      }

      export default AutoHeightImage;

**Comment by daybrush** [comment]
@holyfrog666 

hi I guess it's because Image doesn't have `loading="lazy"` ?

It may have its own polyfill. If so, could you try adding <Image `data-grid-lazy="true'` ... />?

1. Will `loading="lazy"` be expressed well in html?
2. If not, try using `useResizeObserver: true`.

**Comment by holyfrog666** [comment]
> @holyfrog666
> 
> hi I guess it's because Image doesn't have `loading="lazy"` ?
> 
> It may have its own polyfill. If so, could you try adding <Image `data-grid-lazy="true'` ... />?
> 
> 1. Will `loading="lazy"` be expressed well in html?
> 2. If not, try using `useResizeObserver: true`.

Thanks my bro @daybrush ,

Unfortunatly I already used loading="lazy" and tried like below, But It's not worked.
Yeah It seems MasonryInifinteGrid behaves like <JustifiedInfiniteGrid>
And I tried [ way 1 ] which you recommend but it's all fail.

![image](https://github.com/naver/egjs-infinitegrid/assets/50097619/fc3ff9e7-bb7d-4cc8-bbbb-40812e9e3bf2)


I don't know exactly why Masonry didn't behave normal Masonry, but Justfied still.

Also I have to check it out useResizeObserver: true ( I'm not sure If it is just what I knew already, do you mean the props on Image or Masonry component? )

**Comment by daybrush** [comment]
@holyfrog666

**Comment by daybrush** [comment]
@holyfrog666 

Any difference from this demo? What option are you using?

https://codesandbox.io/s/condescending-wilbur-h3upzv

**Comment by holyfrog666** [comment]
> @holyfrog666
> 
> Any difference from this demo? What option are you using?
> 
> https://codesandbox.io/s/condescending-wilbur-h3upzv

Thanks for coming again.

I can't check that codesandbox URL with this alert "sandbox not found", can you check again bro?

I'm using `<MasonryInfinitedGrid>` Component like this.

<MasonryInfiniteGrid
    gap={20}
    onRequestAppend={(e) => {
      const nextGroupKey = (e.groupKey !== null && e.groupKey !== undefined ? +e.groupKey : 0) + 1;

      setItems([
        ...items,
        ...getItems(nextGroupKey, 10),
      ]);
    }}
  >
    {items.map((item) => <Item data-grid-groupkey={item.groupKey} key={item.key} num={item.key} />)}
  </MasonryInfiniteGrid>;

**Comment by daybrush** [comment]
@holyfrog666 

Changed codesandbox to public.
If it's a personal space, contact me via Twitter DM or email in my profile.

**Comment by holyfrog666** [comment]
Demo looks like good, but it's different on my project code. It's weird, I dunno why this happening exactly, but it's not working as you saw above on my code structure. As the demo looks good at my local, something is wrong on my CSS, I guess.

FYI, Have other problems with CSS when it's going on resize, first child and other variable height child is wrap together.
I will try more with my CSS first for fixing this.
