### ISSUE TITLE
width issue && container keyword in tailwind

### ISSUE THREAD

**Issue by adxxtya** [naver/egjs-infinitegrid#543]
- using Next.js 13<
- without typescript
- tailwind css library

## Issue 1
The width when changed(increased) overlaps over other images, the default size are way too small for human eye to perceive.
Yes, I tested the images after making the changes and I have resized the window or refreshed the whole server still to no avail. Maybe, I am dumb and missing out on something very obvious.

## Issue 2
The container keyword are present in both the library and the tailwind css library, so they clash and thus produce two meaning for the same keyword (className="container bg-[orange]"). I can change the keyword specific to tailwind and have a work-around but it is way too much complication in the process for a simple task as such. 

## Tried to reproduce
[code sandbox](https://codesandbox.io/s/modest-ellis-qxxqcx?file=/src/App.tsx)

- willing to participate in helping

**Comment by daybrush** [comment]
@adxxtya 

As for Issue 1, JustifiedGrid maintains the first render size ratio of items.
If you want to change the size of JustifiedInfiniteGrid's items, call `.updateItems(items, { useOrgResize: true })`.

I don't know the meaning of issue2. Are there any overlapping keywords?
Will there be any problems if I change the className?

**Comment by adxxtya** [comment]
I found a work-around for the second issue, the code isn't bugging anymore. Although my first issue was somewhat solved, I'll still try the updateItems method. Thank you 🤝
