### ISSUE TITLE
[svelte] "child" is not defined on clean install

### ISSUE THREAD

**Issue by choibles** [naver/egjs-infinitegrid#544]
## Description
Hi - enjoying the library so far. Thanks! 

Reporting a small, but easy-to-fix issue. The Svelte version has an undefined `child` variable declared in `InfiniteGrid.svelte` on line 56.

## Steps to check or reproduce
Can be seen from a fresh install of `@egjs/svelte-infinitegrid`. See a broken REPL at https://svelte.dev/repl/8736b43e2086454fa75b2f16b0c29148?version=3.44.2 (though I didn't create this).

## Steps to fix
Fix appears as simple as changing the `infoBy(child, i)` call on line 56 in InfiniteGrid.svelte to `infoBy(item, i)`, which I believe is the intent of the function. Have updated in my local version and the library appears to work correctly.

Not an urgent fix at this time, but figured it'd be worth reporting to the library maintainers.

**Comment by daybrush** [comment]
@choibles 


Released as version 4.10.1. Check it again.

**Comment by choibles** [comment]
Fix is verified! Amazing, thank you so much.
