### ISSUE TITLE
When prepended items are layouting, card position is changed.

### ISSUE THREAD

**Issue by sculove** [naver/egjs-infinitegrid#77]
## Description
When prepended items are layouting, card position is changed.
![3dc0d782-cec7-11e7-83b3-edbaa1cb2a85](https://user-images.githubusercontent.com/1383952/33252390-4585487c-d381-11e7-9cb4-bad4348567f5.png)

this is not bug. but we should improve this case.

## Steps to check or reproduce
1. prepend
2. layout(false)

**Comment by younkue** [comment]
change options isEqualSize or add option isFixedSize(?)
